// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.sottovasoluminoso.protobuf.java;

/**
 * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor}
 */
public final class BluetoothGATTDescriptor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor)
    BluetoothGATTDescriptorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BluetoothGATTDescriptor.newBuilder() to construct.
  private BluetoothGATTDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BluetoothGATTDescriptor() {
    uuid_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BluetoothGATTDescriptor();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothGATTDescriptor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothGATTDescriptor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor.class, it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor.Builder.class);
  }

  public static final int UUID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList uuid_;
  /**
   * <code>repeated uint64 uuid = 1;</code>
   * @return A list containing the uuid.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getUuidList() {
    return uuid_;
  }
  /**
   * <code>repeated uint64 uuid = 1;</code>
   * @return The count of uuid.
   */
  public int getUuidCount() {
    return uuid_.size();
  }
  /**
   * <code>repeated uint64 uuid = 1;</code>
   * @param index The index of the element to return.
   * @return The uuid at the given index.
   */
  public long getUuid(int index) {
    return uuid_.getLong(index);
  }
  private int uuidMemoizedSerializedSize = -1;

  public static final int HANDLE_FIELD_NUMBER = 2;
  private int handle_ = 0;
  /**
   * <code>uint32 handle = 2;</code>
   * @return The handle.
   */
  @java.lang.Override
  public int getHandle() {
    return handle_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getUuidList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(uuidMemoizedSerializedSize);
    }
    for (int i = 0; i < uuid_.size(); i++) {
      output.writeUInt64NoTag(uuid_.getLong(i));
    }
    if (handle_ != 0) {
      output.writeUInt32(2, handle_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < uuid_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(uuid_.getLong(i));
      }
      size += dataSize;
      if (!getUuidList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      uuidMemoizedSerializedSize = dataSize;
    }
    if (handle_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, handle_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor)) {
      return super.equals(obj);
    }
    it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor other = (it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor) obj;

    if (!getUuidList()
        .equals(other.getUuidList())) return false;
    if (getHandle()
        != other.getHandle()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUuidCount() > 0) {
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuidList().hashCode();
    }
    hash = (37 * hash) + HANDLE_FIELD_NUMBER;
    hash = (53 * hash) + getHandle();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor)
      it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothGATTDescriptor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothGATTDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor.class, it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor.Builder.class);
    }

    // Construct using it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uuid_ = emptyLongList();
      handle_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothGATTDescriptor_descriptor;
    }

    @java.lang.Override
    public it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor getDefaultInstanceForType() {
      return it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor.getDefaultInstance();
    }

    @java.lang.Override
    public it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor build() {
      it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor buildPartial() {
      it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor result = new it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        uuid_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.uuid_ = uuid_;
    }

    private void buildPartial0(it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.handle_ = handle_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor) {
        return mergeFrom((it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor other) {
      if (other == it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor.getDefaultInstance()) return this;
      if (!other.uuid_.isEmpty()) {
        if (uuid_.isEmpty()) {
          uuid_ = other.uuid_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureUuidIsMutable();
          uuid_.addAll(other.uuid_);
        }
        onChanged();
      }
      if (other.getHandle() != 0) {
        setHandle(other.getHandle());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              long v = input.readUInt64();
              ensureUuidIsMutable();
              uuid_.addLong(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureUuidIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                uuid_.addLong(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 16: {
              handle_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList uuid_ = emptyLongList();
    private void ensureUuidIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        uuid_ = mutableCopy(uuid_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated uint64 uuid = 1;</code>
     * @return A list containing the uuid.
     */
    public java.util.List<java.lang.Long>
        getUuidList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(uuid_) : uuid_;
    }
    /**
     * <code>repeated uint64 uuid = 1;</code>
     * @return The count of uuid.
     */
    public int getUuidCount() {
      return uuid_.size();
    }
    /**
     * <code>repeated uint64 uuid = 1;</code>
     * @param index The index of the element to return.
     * @return The uuid at the given index.
     */
    public long getUuid(int index) {
      return uuid_.getLong(index);
    }
    /**
     * <code>repeated uint64 uuid = 1;</code>
     * @param index The index to set the value at.
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        int index, long value) {
      
      ensureUuidIsMutable();
      uuid_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 uuid = 1;</code>
     * @param value The uuid to add.
     * @return This builder for chaining.
     */
    public Builder addUuid(long value) {
      
      ensureUuidIsMutable();
      uuid_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 uuid = 1;</code>
     * @param values The uuid to add.
     * @return This builder for chaining.
     */
    public Builder addAllUuid(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureUuidIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, uuid_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint64 uuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      uuid_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private int handle_ ;
    /**
     * <code>uint32 handle = 2;</code>
     * @return The handle.
     */
    @java.lang.Override
    public int getHandle() {
      return handle_;
    }
    /**
     * <code>uint32 handle = 2;</code>
     * @param value The handle to set.
     * @return This builder for chaining.
     */
    public Builder setHandle(int value) {
      
      handle_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 handle = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHandle() {
      bitField0_ = (bitField0_ & ~0x00000002);
      handle_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor)
  }

  // @@protoc_insertion_point(class_scope:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor)
  private static final it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor();
  }

  public static it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BluetoothGATTDescriptor>
      PARSER = new com.google.protobuf.AbstractParser<BluetoothGATTDescriptor>() {
    @java.lang.Override
    public BluetoothGATTDescriptor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BluetoothGATTDescriptor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BluetoothGATTDescriptor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTDescriptor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

