//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

package it.achdjian.sottovasoluminoso.protobuf.java;

@kotlin.jvm.JvmName("-initializebluetoothGATTNotifyDataResponse")
public inline fun bluetoothGATTNotifyDataResponse(block: it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponseKt.Dsl.() -> kotlin.Unit): it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponse =
  it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponseKt.Dsl._create(it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponse.newBuilder()).apply { block() }._build()
public object BluetoothGATTNotifyDataResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponse = _builder.build()

    /**
     * <code>uint64 address = 1;</code>
     */
    public var address: kotlin.Long
      @JvmName("getAddress")
      get() = _builder.getAddress()
      @JvmName("setAddress")
      set(value) {
        _builder.setAddress(value)
      }
    /**
     * <code>uint64 address = 1;</code>
     */
    public fun clearAddress() {
      _builder.clearAddress()
    }

    /**
     * <code>uint32 handle = 2;</code>
     */
    public var handle: kotlin.Int
      @JvmName("getHandle")
      get() = _builder.getHandle()
      @JvmName("setHandle")
      set(value) {
        _builder.setHandle(value)
      }
    /**
     * <code>uint32 handle = 2;</code>
     */
    public fun clearHandle() {
      _builder.clearHandle()
    }

    /**
     * <code>bytes data = 3;</code>
     */
    public var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <code>bytes data = 3;</code>
     */
    public fun clearData() {
      _builder.clearData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponse.copy(block: it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponseKt.Dsl.() -> kotlin.Unit): it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponse =
  it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTNotifyDataResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

