// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.sottovasoluminoso.protobuf.java;

public interface CoverStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.achdjian.sottovasoluminoso.protobuf.java.CoverStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed32 key = 1;</code>
   * @return The key.
   */
  int getKey();

  /**
   * <pre>
   * legacy: state has been removed in 1.13
   * clients/servers must still send/accept it until the next protocol change
   * </pre>
   *
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.LegacyCoverState legacy_state = 2;</code>
   * @return The enum numeric value on the wire for legacyState.
   */
  int getLegacyStateValue();
  /**
   * <pre>
   * legacy: state has been removed in 1.13
   * clients/servers must still send/accept it until the next protocol change
   * </pre>
   *
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.LegacyCoverState legacy_state = 2;</code>
   * @return The legacyState.
   */
  it.achdjian.sottovasoluminoso.protobuf.java.LegacyCoverState getLegacyState();

  /**
   * <code>float position = 3;</code>
   * @return The position.
   */
  float getPosition();

  /**
   * <code>float tilt = 4;</code>
   * @return The tilt.
   */
  float getTilt();

  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.CoverOperation current_operation = 5;</code>
   * @return The enum numeric value on the wire for currentOperation.
   */
  int getCurrentOperationValue();
  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.CoverOperation current_operation = 5;</code>
   * @return The currentOperation.
   */
  it.achdjian.sottovasoluminoso.protobuf.java.CoverOperation getCurrentOperation();
}
