//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

package it.achdjian.sottovasoluminoso.protobuf.java;

@kotlin.jvm.JvmName("-initializedisconnectResponse")
public inline fun disconnectResponse(block: it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponseKt.Dsl.() -> kotlin.Unit): it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponse =
  it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponseKt.Dsl._create(it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponse.newBuilder()).apply { block() }._build()
public object DisconnectResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponse.copy(block: it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponseKt.Dsl.() -> kotlin.Unit): it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponse =
  it.achdjian.sottovasoluminoso.protobuf.java.DisconnectResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

