// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.sottovasoluminoso.protobuf.java;

/**
 * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument}
 */
public final class ExecuteServiceArgument extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument)
    ExecuteServiceArgumentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteServiceArgument.newBuilder() to construct.
  private ExecuteServiceArgument(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteServiceArgument() {
    string_ = "";
    boolArray_ = emptyBooleanList();
    intArray_ = emptyIntList();
    floatArray_ = emptyFloatList();
    stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecuteServiceArgument();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_ExecuteServiceArgument_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_ExecuteServiceArgument_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument.class, it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument.Builder.class);
  }

  public static final int BOOL__FIELD_NUMBER = 1;
  private boolean bool_ = false;
  /**
   * <code>bool bool_ = 1;</code>
   * @return The bool.
   */
  @java.lang.Override
  public boolean getBool() {
    return bool_;
  }

  public static final int LEGACY_INT_FIELD_NUMBER = 2;
  private int legacyInt_ = 0;
  /**
   * <code>int32 legacy_int = 2;</code>
   * @return The legacyInt.
   */
  @java.lang.Override
  public int getLegacyInt() {
    return legacyInt_;
  }

  public static final int FLOAT__FIELD_NUMBER = 3;
  private float float_ = 0F;
  /**
   * <code>float float_ = 3;</code>
   * @return The float.
   */
  @java.lang.Override
  public float getFloat() {
    return float_;
  }

  public static final int STRING__FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object string_ = "";
  /**
   * <code>string string_ = 4;</code>
   * @return The string.
   */
  @java.lang.Override
  public java.lang.String getString() {
    java.lang.Object ref = string_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      string_ = s;
      return s;
    }
  }
  /**
   * <code>string string_ = 4;</code>
   * @return The bytes for string.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringBytes() {
    java.lang.Object ref = string_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      string_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INT__FIELD_NUMBER = 5;
  private int int_ = 0;
  /**
   * <pre>
   * ESPHome 1.14 (api v1.3) make int a signed value
   * </pre>
   *
   * <code>sint32 int_ = 5;</code>
   * @return The int.
   */
  @java.lang.Override
  public int getInt() {
    return int_;
  }

  public static final int BOOL_ARRAY_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.BooleanList boolArray_;
  /**
   * <code>repeated bool bool_array = 6 [packed = false];</code>
   * @return A list containing the boolArray.
   */
  @java.lang.Override
  public java.util.List<java.lang.Boolean>
      getBoolArrayList() {
    return boolArray_;
  }
  /**
   * <code>repeated bool bool_array = 6 [packed = false];</code>
   * @return The count of boolArray.
   */
  public int getBoolArrayCount() {
    return boolArray_.size();
  }
  /**
   * <code>repeated bool bool_array = 6 [packed = false];</code>
   * @param index The index of the element to return.
   * @return The boolArray at the given index.
   */
  public boolean getBoolArray(int index) {
    return boolArray_.getBoolean(index);
  }

  public static final int INT_ARRAY_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList intArray_;
  /**
   * <code>repeated sint32 int_array = 7 [packed = false];</code>
   * @return A list containing the intArray.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getIntArrayList() {
    return intArray_;
  }
  /**
   * <code>repeated sint32 int_array = 7 [packed = false];</code>
   * @return The count of intArray.
   */
  public int getIntArrayCount() {
    return intArray_.size();
  }
  /**
   * <code>repeated sint32 int_array = 7 [packed = false];</code>
   * @param index The index of the element to return.
   * @return The intArray at the given index.
   */
  public int getIntArray(int index) {
    return intArray_.getInt(index);
  }

  public static final int FLOAT_ARRAY_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList floatArray_;
  /**
   * <code>repeated float float_array = 8 [packed = false];</code>
   * @return A list containing the floatArray.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getFloatArrayList() {
    return floatArray_;
  }
  /**
   * <code>repeated float float_array = 8 [packed = false];</code>
   * @return The count of floatArray.
   */
  public int getFloatArrayCount() {
    return floatArray_.size();
  }
  /**
   * <code>repeated float float_array = 8 [packed = false];</code>
   * @param index The index of the element to return.
   * @return The floatArray at the given index.
   */
  public float getFloatArray(int index) {
    return floatArray_.getFloat(index);
  }

  public static final int STRING_ARRAY_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList stringArray_;
  /**
   * <code>repeated string string_array = 9;</code>
   * @return A list containing the stringArray.
   */
  public com.google.protobuf.ProtocolStringList
      getStringArrayList() {
    return stringArray_;
  }
  /**
   * <code>repeated string string_array = 9;</code>
   * @return The count of stringArray.
   */
  public int getStringArrayCount() {
    return stringArray_.size();
  }
  /**
   * <code>repeated string string_array = 9;</code>
   * @param index The index of the element to return.
   * @return The stringArray at the given index.
   */
  public java.lang.String getStringArray(int index) {
    return stringArray_.get(index);
  }
  /**
   * <code>repeated string string_array = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stringArray at the given index.
   */
  public com.google.protobuf.ByteString
      getStringArrayBytes(int index) {
    return stringArray_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bool_ != false) {
      output.writeBool(1, bool_);
    }
    if (legacyInt_ != 0) {
      output.writeInt32(2, legacyInt_);
    }
    if (java.lang.Float.floatToRawIntBits(float_) != 0) {
      output.writeFloat(3, float_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(string_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, string_);
    }
    if (int_ != 0) {
      output.writeSInt32(5, int_);
    }
    for (int i = 0; i < boolArray_.size(); i++) {
      output.writeBool(6, boolArray_.getBoolean(i));
    }
    for (int i = 0; i < intArray_.size(); i++) {
      output.writeSInt32(7, intArray_.getInt(i));
    }
    for (int i = 0; i < floatArray_.size(); i++) {
      output.writeFloat(8, floatArray_.getFloat(i));
    }
    for (int i = 0; i < stringArray_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, stringArray_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bool_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, bool_);
    }
    if (legacyInt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, legacyInt_);
    }
    if (java.lang.Float.floatToRawIntBits(float_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, float_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(string_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, string_);
    }
    if (int_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(5, int_);
    }
    {
      int dataSize = 0;
      dataSize = 1 * getBoolArrayList().size();
      size += dataSize;
      size += 1 * getBoolArrayList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < intArray_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeSInt32SizeNoTag(intArray_.getInt(i));
      }
      size += dataSize;
      size += 1 * getIntArrayList().size();
    }
    {
      int dataSize = 0;
      dataSize = 4 * getFloatArrayList().size();
      size += dataSize;
      size += 1 * getFloatArrayList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < stringArray_.size(); i++) {
        dataSize += computeStringSizeNoTag(stringArray_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStringArrayList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument)) {
      return super.equals(obj);
    }
    it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument other = (it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument) obj;

    if (getBool()
        != other.getBool()) return false;
    if (getLegacyInt()
        != other.getLegacyInt()) return false;
    if (java.lang.Float.floatToIntBits(getFloat())
        != java.lang.Float.floatToIntBits(
            other.getFloat())) return false;
    if (!getString()
        .equals(other.getString())) return false;
    if (getInt()
        != other.getInt()) return false;
    if (!getBoolArrayList()
        .equals(other.getBoolArrayList())) return false;
    if (!getIntArrayList()
        .equals(other.getIntArrayList())) return false;
    if (!getFloatArrayList()
        .equals(other.getFloatArrayList())) return false;
    if (!getStringArrayList()
        .equals(other.getStringArrayList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOL__FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBool());
    hash = (37 * hash) + LEGACY_INT_FIELD_NUMBER;
    hash = (53 * hash) + getLegacyInt();
    hash = (37 * hash) + FLOAT__FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFloat());
    hash = (37 * hash) + STRING__FIELD_NUMBER;
    hash = (53 * hash) + getString().hashCode();
    hash = (37 * hash) + INT__FIELD_NUMBER;
    hash = (53 * hash) + getInt();
    if (getBoolArrayCount() > 0) {
      hash = (37 * hash) + BOOL_ARRAY_FIELD_NUMBER;
      hash = (53 * hash) + getBoolArrayList().hashCode();
    }
    if (getIntArrayCount() > 0) {
      hash = (37 * hash) + INT_ARRAY_FIELD_NUMBER;
      hash = (53 * hash) + getIntArrayList().hashCode();
    }
    if (getFloatArrayCount() > 0) {
      hash = (37 * hash) + FLOAT_ARRAY_FIELD_NUMBER;
      hash = (53 * hash) + getFloatArrayList().hashCode();
    }
    if (getStringArrayCount() > 0) {
      hash = (37 * hash) + STRING_ARRAY_FIELD_NUMBER;
      hash = (53 * hash) + getStringArrayList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument)
      it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgumentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_ExecuteServiceArgument_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_ExecuteServiceArgument_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument.class, it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument.Builder.class);
    }

    // Construct using it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bool_ = false;
      legacyInt_ = 0;
      float_ = 0F;
      string_ = "";
      int_ = 0;
      boolArray_ = emptyBooleanList();
      intArray_ = emptyIntList();
      floatArray_ = emptyFloatList();
      stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_ExecuteServiceArgument_descriptor;
    }

    @java.lang.Override
    public it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument getDefaultInstanceForType() {
      return it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument.getDefaultInstance();
    }

    @java.lang.Override
    public it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument build() {
      it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument buildPartial() {
      it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument result = new it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument result) {
      if (((bitField0_ & 0x00000020) != 0)) {
        boolArray_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.boolArray_ = boolArray_;
      if (((bitField0_ & 0x00000040) != 0)) {
        intArray_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.intArray_ = intArray_;
      if (((bitField0_ & 0x00000080) != 0)) {
        floatArray_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.floatArray_ = floatArray_;
      if (((bitField0_ & 0x00000100) != 0)) {
        stringArray_ = stringArray_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000100);
      }
      result.stringArray_ = stringArray_;
    }

    private void buildPartial0(it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bool_ = bool_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.legacyInt_ = legacyInt_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.float_ = float_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.string_ = string_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.int_ = int_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument) {
        return mergeFrom((it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument other) {
      if (other == it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument.getDefaultInstance()) return this;
      if (other.getBool() != false) {
        setBool(other.getBool());
      }
      if (other.getLegacyInt() != 0) {
        setLegacyInt(other.getLegacyInt());
      }
      if (other.getFloat() != 0F) {
        setFloat(other.getFloat());
      }
      if (!other.getString().isEmpty()) {
        string_ = other.string_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getInt() != 0) {
        setInt(other.getInt());
      }
      if (!other.boolArray_.isEmpty()) {
        if (boolArray_.isEmpty()) {
          boolArray_ = other.boolArray_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensureBoolArrayIsMutable();
          boolArray_.addAll(other.boolArray_);
        }
        onChanged();
      }
      if (!other.intArray_.isEmpty()) {
        if (intArray_.isEmpty()) {
          intArray_ = other.intArray_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensureIntArrayIsMutable();
          intArray_.addAll(other.intArray_);
        }
        onChanged();
      }
      if (!other.floatArray_.isEmpty()) {
        if (floatArray_.isEmpty()) {
          floatArray_ = other.floatArray_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureFloatArrayIsMutable();
          floatArray_.addAll(other.floatArray_);
        }
        onChanged();
      }
      if (!other.stringArray_.isEmpty()) {
        if (stringArray_.isEmpty()) {
          stringArray_ = other.stringArray_;
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          ensureStringArrayIsMutable();
          stringArray_.addAll(other.stringArray_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bool_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              legacyInt_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 29: {
              float_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 34: {
              string_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              int_ = input.readSInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              boolean v = input.readBool();
              ensureBoolArrayIsMutable();
              boolArray_.addBoolean(v);
              break;
            } // case 48
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureBoolArrayIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                boolArray_.addBoolean(input.readBool());
              }
              input.popLimit(limit);
              break;
            } // case 50
            case 56: {
              int v = input.readSInt32();
              ensureIntArrayIsMutable();
              intArray_.addInt(v);
              break;
            } // case 56
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureIntArrayIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                intArray_.addInt(input.readSInt32());
              }
              input.popLimit(limit);
              break;
            } // case 58
            case 69: {
              float v = input.readFloat();
              ensureFloatArrayIsMutable();
              floatArray_.addFloat(v);
              break;
            } // case 69
            case 66: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureFloatArrayIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                floatArray_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 66
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureStringArrayIsMutable();
              stringArray_.add(s);
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean bool_ ;
    /**
     * <code>bool bool_ = 1;</code>
     * @return The bool.
     */
    @java.lang.Override
    public boolean getBool() {
      return bool_;
    }
    /**
     * <code>bool bool_ = 1;</code>
     * @param value The bool to set.
     * @return This builder for chaining.
     */
    public Builder setBool(boolean value) {
      
      bool_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool bool_ = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBool() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bool_ = false;
      onChanged();
      return this;
    }

    private int legacyInt_ ;
    /**
     * <code>int32 legacy_int = 2;</code>
     * @return The legacyInt.
     */
    @java.lang.Override
    public int getLegacyInt() {
      return legacyInt_;
    }
    /**
     * <code>int32 legacy_int = 2;</code>
     * @param value The legacyInt to set.
     * @return This builder for chaining.
     */
    public Builder setLegacyInt(int value) {
      
      legacyInt_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 legacy_int = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLegacyInt() {
      bitField0_ = (bitField0_ & ~0x00000002);
      legacyInt_ = 0;
      onChanged();
      return this;
    }

    private float float_ ;
    /**
     * <code>float float_ = 3;</code>
     * @return The float.
     */
    @java.lang.Override
    public float getFloat() {
      return float_;
    }
    /**
     * <code>float float_ = 3;</code>
     * @param value The float to set.
     * @return This builder for chaining.
     */
    public Builder setFloat(float value) {
      
      float_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float float_ = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloat() {
      bitField0_ = (bitField0_ & ~0x00000004);
      float_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object string_ = "";
    /**
     * <code>string string_ = 4;</code>
     * @return The string.
     */
    public java.lang.String getString() {
      java.lang.Object ref = string_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string_ = 4;</code>
     * @return The bytes for string.
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = string_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string_ = 4;</code>
     * @param value The string to set.
     * @return This builder for chaining.
     */
    public Builder setString(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      string_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string string_ = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearString() {
      string_ = getDefaultInstance().getString();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string string_ = 4;</code>
     * @param value The bytes for string to set.
     * @return This builder for chaining.
     */
    public Builder setStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      string_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int int_ ;
    /**
     * <pre>
     * ESPHome 1.14 (api v1.3) make int a signed value
     * </pre>
     *
     * <code>sint32 int_ = 5;</code>
     * @return The int.
     */
    @java.lang.Override
    public int getInt() {
      return int_;
    }
    /**
     * <pre>
     * ESPHome 1.14 (api v1.3) make int a signed value
     * </pre>
     *
     * <code>sint32 int_ = 5;</code>
     * @param value The int to set.
     * @return This builder for chaining.
     */
    public Builder setInt(int value) {
      
      int_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ESPHome 1.14 (api v1.3) make int a signed value
     * </pre>
     *
     * <code>sint32 int_ = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt() {
      bitField0_ = (bitField0_ & ~0x00000010);
      int_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.BooleanList boolArray_ = emptyBooleanList();
    private void ensureBoolArrayIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        boolArray_ = mutableCopy(boolArray_);
        bitField0_ |= 0x00000020;
      }
    }
    /**
     * <code>repeated bool bool_array = 6 [packed = false];</code>
     * @return A list containing the boolArray.
     */
    public java.util.List<java.lang.Boolean>
        getBoolArrayList() {
      return ((bitField0_ & 0x00000020) != 0) ?
               java.util.Collections.unmodifiableList(boolArray_) : boolArray_;
    }
    /**
     * <code>repeated bool bool_array = 6 [packed = false];</code>
     * @return The count of boolArray.
     */
    public int getBoolArrayCount() {
      return boolArray_.size();
    }
    /**
     * <code>repeated bool bool_array = 6 [packed = false];</code>
     * @param index The index of the element to return.
     * @return The boolArray at the given index.
     */
    public boolean getBoolArray(int index) {
      return boolArray_.getBoolean(index);
    }
    /**
     * <code>repeated bool bool_array = 6 [packed = false];</code>
     * @param index The index to set the value at.
     * @param value The boolArray to set.
     * @return This builder for chaining.
     */
    public Builder setBoolArray(
        int index, boolean value) {
      
      ensureBoolArrayIsMutable();
      boolArray_.setBoolean(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool bool_array = 6 [packed = false];</code>
     * @param value The boolArray to add.
     * @return This builder for chaining.
     */
    public Builder addBoolArray(boolean value) {
      
      ensureBoolArrayIsMutable();
      boolArray_.addBoolean(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool bool_array = 6 [packed = false];</code>
     * @param values The boolArray to add.
     * @return This builder for chaining.
     */
    public Builder addAllBoolArray(
        java.lang.Iterable<? extends java.lang.Boolean> values) {
      ensureBoolArrayIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, boolArray_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool bool_array = 6 [packed = false];</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolArray() {
      boolArray_ = emptyBooleanList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList intArray_ = emptyIntList();
    private void ensureIntArrayIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        intArray_ = mutableCopy(intArray_);
        bitField0_ |= 0x00000040;
      }
    }
    /**
     * <code>repeated sint32 int_array = 7 [packed = false];</code>
     * @return A list containing the intArray.
     */
    public java.util.List<java.lang.Integer>
        getIntArrayList() {
      return ((bitField0_ & 0x00000040) != 0) ?
               java.util.Collections.unmodifiableList(intArray_) : intArray_;
    }
    /**
     * <code>repeated sint32 int_array = 7 [packed = false];</code>
     * @return The count of intArray.
     */
    public int getIntArrayCount() {
      return intArray_.size();
    }
    /**
     * <code>repeated sint32 int_array = 7 [packed = false];</code>
     * @param index The index of the element to return.
     * @return The intArray at the given index.
     */
    public int getIntArray(int index) {
      return intArray_.getInt(index);
    }
    /**
     * <code>repeated sint32 int_array = 7 [packed = false];</code>
     * @param index The index to set the value at.
     * @param value The intArray to set.
     * @return This builder for chaining.
     */
    public Builder setIntArray(
        int index, int value) {
      
      ensureIntArrayIsMutable();
      intArray_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint32 int_array = 7 [packed = false];</code>
     * @param value The intArray to add.
     * @return This builder for chaining.
     */
    public Builder addIntArray(int value) {
      
      ensureIntArrayIsMutable();
      intArray_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint32 int_array = 7 [packed = false];</code>
     * @param values The intArray to add.
     * @return This builder for chaining.
     */
    public Builder addAllIntArray(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureIntArrayIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, intArray_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint32 int_array = 7 [packed = false];</code>
     * @return This builder for chaining.
     */
    public Builder clearIntArray() {
      intArray_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList floatArray_ = emptyFloatList();
    private void ensureFloatArrayIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        floatArray_ = mutableCopy(floatArray_);
        bitField0_ |= 0x00000080;
      }
    }
    /**
     * <code>repeated float float_array = 8 [packed = false];</code>
     * @return A list containing the floatArray.
     */
    public java.util.List<java.lang.Float>
        getFloatArrayList() {
      return ((bitField0_ & 0x00000080) != 0) ?
               java.util.Collections.unmodifiableList(floatArray_) : floatArray_;
    }
    /**
     * <code>repeated float float_array = 8 [packed = false];</code>
     * @return The count of floatArray.
     */
    public int getFloatArrayCount() {
      return floatArray_.size();
    }
    /**
     * <code>repeated float float_array = 8 [packed = false];</code>
     * @param index The index of the element to return.
     * @return The floatArray at the given index.
     */
    public float getFloatArray(int index) {
      return floatArray_.getFloat(index);
    }
    /**
     * <code>repeated float float_array = 8 [packed = false];</code>
     * @param index The index to set the value at.
     * @param value The floatArray to set.
     * @return This builder for chaining.
     */
    public Builder setFloatArray(
        int index, float value) {
      
      ensureFloatArrayIsMutable();
      floatArray_.setFloat(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float float_array = 8 [packed = false];</code>
     * @param value The floatArray to add.
     * @return This builder for chaining.
     */
    public Builder addFloatArray(float value) {
      
      ensureFloatArrayIsMutable();
      floatArray_.addFloat(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float float_array = 8 [packed = false];</code>
     * @param values The floatArray to add.
     * @return This builder for chaining.
     */
    public Builder addAllFloatArray(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureFloatArrayIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, floatArray_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float float_array = 8 [packed = false];</code>
     * @return This builder for chaining.
     */
    public Builder clearFloatArray() {
      floatArray_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureStringArrayIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        stringArray_ = new com.google.protobuf.LazyStringArrayList(stringArray_);
        bitField0_ |= 0x00000100;
       }
    }
    /**
     * <code>repeated string string_array = 9;</code>
     * @return A list containing the stringArray.
     */
    public com.google.protobuf.ProtocolStringList
        getStringArrayList() {
      return stringArray_.getUnmodifiableView();
    }
    /**
     * <code>repeated string string_array = 9;</code>
     * @return The count of stringArray.
     */
    public int getStringArrayCount() {
      return stringArray_.size();
    }
    /**
     * <code>repeated string string_array = 9;</code>
     * @param index The index of the element to return.
     * @return The stringArray at the given index.
     */
    public java.lang.String getStringArray(int index) {
      return stringArray_.get(index);
    }
    /**
     * <code>repeated string string_array = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stringArray at the given index.
     */
    public com.google.protobuf.ByteString
        getStringArrayBytes(int index) {
      return stringArray_.getByteString(index);
    }
    /**
     * <code>repeated string string_array = 9;</code>
     * @param index The index to set the value at.
     * @param value The stringArray to set.
     * @return This builder for chaining.
     */
    public Builder setStringArray(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStringArrayIsMutable();
      stringArray_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_array = 9;</code>
     * @param value The stringArray to add.
     * @return This builder for chaining.
     */
    public Builder addStringArray(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStringArrayIsMutable();
      stringArray_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_array = 9;</code>
     * @param values The stringArray to add.
     * @return This builder for chaining.
     */
    public Builder addAllStringArray(
        java.lang.Iterable<java.lang.String> values) {
      ensureStringArrayIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stringArray_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_array = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringArray() {
      stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string string_array = 9;</code>
     * @param value The bytes of the stringArray to add.
     * @return This builder for chaining.
     */
    public Builder addStringArrayBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureStringArrayIsMutable();
      stringArray_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument)
  }

  // @@protoc_insertion_point(class_scope:it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument)
  private static final it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument();
  }

  public static it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteServiceArgument>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteServiceArgument>() {
    @java.lang.Override
    public ExecuteServiceArgument parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteServiceArgument> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteServiceArgument> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public it.achdjian.sottovasoluminoso.protobuf.java.ExecuteServiceArgument getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

