//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

package it.achdjian.sottovasoluminoso.protobuf.java;

@kotlin.jvm.JvmName("-initializefanCommandRequest")
public inline fun fanCommandRequest(block: it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequestKt.Dsl.() -> kotlin.Unit): it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest =
  it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequestKt.Dsl._create(it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.newBuilder()).apply { block() }._build()
public object FanCommandRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest = _builder.build()

    /**
     * <code>fixed32 key = 1;</code>
     */
    public var key: kotlin.Int
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <code>fixed32 key = 1;</code>
     */
    public fun clearKey() {
      _builder.clearKey()
    }

    /**
     * <code>bool has_state = 2;</code>
     */
    public var hasState: kotlin.Boolean
      @JvmName("getHasState")
      get() = _builder.getHasState()
      @JvmName("setHasState")
      set(value) {
        _builder.setHasState(value)
      }
    /**
     * <code>bool has_state = 2;</code>
     */
    public fun clearHasState() {
      _builder.clearHasState()
    }

    /**
     * <code>bool state = 3;</code>
     */
    public var state: kotlin.Boolean
      @JvmName("getState")
      get() = _builder.getState()
      @JvmName("setState")
      set(value) {
        _builder.setState(value)
      }
    /**
     * <code>bool state = 3;</code>
     */
    public fun clearState() {
      _builder.clearState()
    }

    /**
     * <code>bool has_speed = 4 [deprecated = true];</code>
     */
    @kotlin.Deprecated(message = "Field hasSpeed is deprecated") public var hasSpeed: kotlin.Boolean
      @JvmName("getHasSpeed")
      get() = _builder.getHasSpeed()
      @JvmName("setHasSpeed")
      set(value) {
        _builder.setHasSpeed(value)
      }
    /**
     * <code>bool has_speed = 4 [deprecated = true];</code>
     * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.has_speed is deprecated.
     *     See api.proto;l=389
     */
    public fun clearHasSpeed() {
      _builder.clearHasSpeed()
    }

    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanSpeed speed = 5 [deprecated = true];</code>
     */
    @kotlin.Deprecated(message = "Field speed is deprecated") public var speed: it.achdjian.sottovasoluminoso.protobuf.java.FanSpeed
      @JvmName("getSpeed")
      get() = _builder.getSpeed()
      @JvmName("setSpeed")
      set(value) {
        _builder.setSpeed(value)
      }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanSpeed speed = 5 [deprecated = true];</code>
     * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.speed is deprecated.
     *     See api.proto;l=390
     */
    public fun clearSpeed() {
      _builder.clearSpeed()
    }

    /**
     * <code>bool has_oscillating = 6;</code>
     */
    public var hasOscillating: kotlin.Boolean
      @JvmName("getHasOscillating")
      get() = _builder.getHasOscillating()
      @JvmName("setHasOscillating")
      set(value) {
        _builder.setHasOscillating(value)
      }
    /**
     * <code>bool has_oscillating = 6;</code>
     */
    public fun clearHasOscillating() {
      _builder.clearHasOscillating()
    }

    /**
     * <code>bool oscillating = 7;</code>
     */
    public var oscillating: kotlin.Boolean
      @JvmName("getOscillating")
      get() = _builder.getOscillating()
      @JvmName("setOscillating")
      set(value) {
        _builder.setOscillating(value)
      }
    /**
     * <code>bool oscillating = 7;</code>
     */
    public fun clearOscillating() {
      _builder.clearOscillating()
    }

    /**
     * <code>bool has_direction = 8;</code>
     */
    public var hasDirection: kotlin.Boolean
      @JvmName("getHasDirection")
      get() = _builder.getHasDirection()
      @JvmName("setHasDirection")
      set(value) {
        _builder.setHasDirection(value)
      }
    /**
     * <code>bool has_direction = 8;</code>
     */
    public fun clearHasDirection() {
      _builder.clearHasDirection()
    }

    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanDirection direction = 9;</code>
     */
    public var direction: it.achdjian.sottovasoluminoso.protobuf.java.FanDirection
      @JvmName("getDirection")
      get() = _builder.getDirection()
      @JvmName("setDirection")
      set(value) {
        _builder.setDirection(value)
      }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanDirection direction = 9;</code>
     */
    public fun clearDirection() {
      _builder.clearDirection()
    }

    /**
     * <code>bool has_speed_level = 10;</code>
     */
    public var hasSpeedLevel: kotlin.Boolean
      @JvmName("getHasSpeedLevel")
      get() = _builder.getHasSpeedLevel()
      @JvmName("setHasSpeedLevel")
      set(value) {
        _builder.setHasSpeedLevel(value)
      }
    /**
     * <code>bool has_speed_level = 10;</code>
     */
    public fun clearHasSpeedLevel() {
      _builder.clearHasSpeedLevel()
    }

    /**
     * <code>int32 speed_level = 11;</code>
     */
    public var speedLevel: kotlin.Int
      @JvmName("getSpeedLevel")
      get() = _builder.getSpeedLevel()
      @JvmName("setSpeedLevel")
      set(value) {
        _builder.setSpeedLevel(value)
      }
    /**
     * <code>int32 speed_level = 11;</code>
     */
    public fun clearSpeedLevel() {
      _builder.clearSpeedLevel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.copy(block: it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequestKt.Dsl.() -> kotlin.Unit): it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest =
  it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

