// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.sottovasoluminoso.protobuf.java;

/**
 * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse}
 */
public final class LightStateResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse)
    LightStateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LightStateResponse.newBuilder() to construct.
  private LightStateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LightStateResponse() {
    colorMode_ = 0;
    effect_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LightStateResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_LightStateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_LightStateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse.class, it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse.Builder.class);
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private int key_ = 0;
  /**
   * <code>fixed32 key = 1;</code>
   * @return The key.
   */
  @java.lang.Override
  public int getKey() {
    return key_;
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private boolean state_ = false;
  /**
   * <code>bool state = 2;</code>
   * @return The state.
   */
  @java.lang.Override
  public boolean getState() {
    return state_;
  }

  public static final int BRIGHTNESS_FIELD_NUMBER = 3;
  private float brightness_ = 0F;
  /**
   * <code>float brightness = 3;</code>
   * @return The brightness.
   */
  @java.lang.Override
  public float getBrightness() {
    return brightness_;
  }

  public static final int COLOR_MODE_FIELD_NUMBER = 11;
  private int colorMode_ = 0;
  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.ColorMode color_mode = 11;</code>
   * @return The enum numeric value on the wire for colorMode.
   */
  @java.lang.Override public int getColorModeValue() {
    return colorMode_;
  }
  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.ColorMode color_mode = 11;</code>
   * @return The colorMode.
   */
  @java.lang.Override public it.achdjian.sottovasoluminoso.protobuf.java.ColorMode getColorMode() {
    it.achdjian.sottovasoluminoso.protobuf.java.ColorMode result = it.achdjian.sottovasoluminoso.protobuf.java.ColorMode.forNumber(colorMode_);
    return result == null ? it.achdjian.sottovasoluminoso.protobuf.java.ColorMode.UNRECOGNIZED : result;
  }

  public static final int COLOR_BRIGHTNESS_FIELD_NUMBER = 10;
  private float colorBrightness_ = 0F;
  /**
   * <code>float color_brightness = 10;</code>
   * @return The colorBrightness.
   */
  @java.lang.Override
  public float getColorBrightness() {
    return colorBrightness_;
  }

  public static final int RED_FIELD_NUMBER = 4;
  private float red_ = 0F;
  /**
   * <code>float red = 4;</code>
   * @return The red.
   */
  @java.lang.Override
  public float getRed() {
    return red_;
  }

  public static final int GREEN_FIELD_NUMBER = 5;
  private float green_ = 0F;
  /**
   * <code>float green = 5;</code>
   * @return The green.
   */
  @java.lang.Override
  public float getGreen() {
    return green_;
  }

  public static final int BLUE_FIELD_NUMBER = 6;
  private float blue_ = 0F;
  /**
   * <code>float blue = 6;</code>
   * @return The blue.
   */
  @java.lang.Override
  public float getBlue() {
    return blue_;
  }

  public static final int WHITE_FIELD_NUMBER = 7;
  private float white_ = 0F;
  /**
   * <code>float white = 7;</code>
   * @return The white.
   */
  @java.lang.Override
  public float getWhite() {
    return white_;
  }

  public static final int COLOR_TEMPERATURE_FIELD_NUMBER = 8;
  private float colorTemperature_ = 0F;
  /**
   * <code>float color_temperature = 8;</code>
   * @return The colorTemperature.
   */
  @java.lang.Override
  public float getColorTemperature() {
    return colorTemperature_;
  }

  public static final int COLD_WHITE_FIELD_NUMBER = 12;
  private float coldWhite_ = 0F;
  /**
   * <code>float cold_white = 12;</code>
   * @return The coldWhite.
   */
  @java.lang.Override
  public float getColdWhite() {
    return coldWhite_;
  }

  public static final int WARM_WHITE_FIELD_NUMBER = 13;
  private float warmWhite_ = 0F;
  /**
   * <code>float warm_white = 13;</code>
   * @return The warmWhite.
   */
  @java.lang.Override
  public float getWarmWhite() {
    return warmWhite_;
  }

  public static final int EFFECT_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object effect_ = "";
  /**
   * <code>string effect = 9;</code>
   * @return The effect.
   */
  @java.lang.Override
  public java.lang.String getEffect() {
    java.lang.Object ref = effect_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      effect_ = s;
      return s;
    }
  }
  /**
   * <code>string effect = 9;</code>
   * @return The bytes for effect.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEffectBytes() {
    java.lang.Object ref = effect_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      effect_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (key_ != 0) {
      output.writeFixed32(1, key_);
    }
    if (state_ != false) {
      output.writeBool(2, state_);
    }
    if (java.lang.Float.floatToRawIntBits(brightness_) != 0) {
      output.writeFloat(3, brightness_);
    }
    if (java.lang.Float.floatToRawIntBits(red_) != 0) {
      output.writeFloat(4, red_);
    }
    if (java.lang.Float.floatToRawIntBits(green_) != 0) {
      output.writeFloat(5, green_);
    }
    if (java.lang.Float.floatToRawIntBits(blue_) != 0) {
      output.writeFloat(6, blue_);
    }
    if (java.lang.Float.floatToRawIntBits(white_) != 0) {
      output.writeFloat(7, white_);
    }
    if (java.lang.Float.floatToRawIntBits(colorTemperature_) != 0) {
      output.writeFloat(8, colorTemperature_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(effect_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, effect_);
    }
    if (java.lang.Float.floatToRawIntBits(colorBrightness_) != 0) {
      output.writeFloat(10, colorBrightness_);
    }
    if (colorMode_ != it.achdjian.sottovasoluminoso.protobuf.java.ColorMode.COLOR_MODE_UNKNOWN.getNumber()) {
      output.writeEnum(11, colorMode_);
    }
    if (java.lang.Float.floatToRawIntBits(coldWhite_) != 0) {
      output.writeFloat(12, coldWhite_);
    }
    if (java.lang.Float.floatToRawIntBits(warmWhite_) != 0) {
      output.writeFloat(13, warmWhite_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (key_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(1, key_);
    }
    if (state_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, state_);
    }
    if (java.lang.Float.floatToRawIntBits(brightness_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, brightness_);
    }
    if (java.lang.Float.floatToRawIntBits(red_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, red_);
    }
    if (java.lang.Float.floatToRawIntBits(green_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, green_);
    }
    if (java.lang.Float.floatToRawIntBits(blue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, blue_);
    }
    if (java.lang.Float.floatToRawIntBits(white_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(7, white_);
    }
    if (java.lang.Float.floatToRawIntBits(colorTemperature_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(8, colorTemperature_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(effect_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, effect_);
    }
    if (java.lang.Float.floatToRawIntBits(colorBrightness_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(10, colorBrightness_);
    }
    if (colorMode_ != it.achdjian.sottovasoluminoso.protobuf.java.ColorMode.COLOR_MODE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, colorMode_);
    }
    if (java.lang.Float.floatToRawIntBits(coldWhite_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(12, coldWhite_);
    }
    if (java.lang.Float.floatToRawIntBits(warmWhite_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(13, warmWhite_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse)) {
      return super.equals(obj);
    }
    it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse other = (it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse) obj;

    if (getKey()
        != other.getKey()) return false;
    if (getState()
        != other.getState()) return false;
    if (java.lang.Float.floatToIntBits(getBrightness())
        != java.lang.Float.floatToIntBits(
            other.getBrightness())) return false;
    if (colorMode_ != other.colorMode_) return false;
    if (java.lang.Float.floatToIntBits(getColorBrightness())
        != java.lang.Float.floatToIntBits(
            other.getColorBrightness())) return false;
    if (java.lang.Float.floatToIntBits(getRed())
        != java.lang.Float.floatToIntBits(
            other.getRed())) return false;
    if (java.lang.Float.floatToIntBits(getGreen())
        != java.lang.Float.floatToIntBits(
            other.getGreen())) return false;
    if (java.lang.Float.floatToIntBits(getBlue())
        != java.lang.Float.floatToIntBits(
            other.getBlue())) return false;
    if (java.lang.Float.floatToIntBits(getWhite())
        != java.lang.Float.floatToIntBits(
            other.getWhite())) return false;
    if (java.lang.Float.floatToIntBits(getColorTemperature())
        != java.lang.Float.floatToIntBits(
            other.getColorTemperature())) return false;
    if (java.lang.Float.floatToIntBits(getColdWhite())
        != java.lang.Float.floatToIntBits(
            other.getColdWhite())) return false;
    if (java.lang.Float.floatToIntBits(getWarmWhite())
        != java.lang.Float.floatToIntBits(
            other.getWarmWhite())) return false;
    if (!getEffect()
        .equals(other.getEffect())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getState());
    hash = (37 * hash) + BRIGHTNESS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBrightness());
    hash = (37 * hash) + COLOR_MODE_FIELD_NUMBER;
    hash = (53 * hash) + colorMode_;
    hash = (37 * hash) + COLOR_BRIGHTNESS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getColorBrightness());
    hash = (37 * hash) + RED_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRed());
    hash = (37 * hash) + GREEN_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getGreen());
    hash = (37 * hash) + BLUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBlue());
    hash = (37 * hash) + WHITE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getWhite());
    hash = (37 * hash) + COLOR_TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getColorTemperature());
    hash = (37 * hash) + COLD_WHITE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getColdWhite());
    hash = (37 * hash) + WARM_WHITE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getWarmWhite());
    hash = (37 * hash) + EFFECT_FIELD_NUMBER;
    hash = (53 * hash) + getEffect().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse)
      it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_LightStateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_LightStateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse.class, it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse.Builder.class);
    }

    // Construct using it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      key_ = 0;
      state_ = false;
      brightness_ = 0F;
      colorMode_ = 0;
      colorBrightness_ = 0F;
      red_ = 0F;
      green_ = 0F;
      blue_ = 0F;
      white_ = 0F;
      colorTemperature_ = 0F;
      coldWhite_ = 0F;
      warmWhite_ = 0F;
      effect_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return it.achdjian.sottovasoluminoso.protobuf.java.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_LightStateResponse_descriptor;
    }

    @java.lang.Override
    public it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse getDefaultInstanceForType() {
      return it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse build() {
      it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse buildPartial() {
      it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse result = new it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.key_ = key_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.state_ = state_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.brightness_ = brightness_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.colorMode_ = colorMode_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.colorBrightness_ = colorBrightness_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.red_ = red_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.green_ = green_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.blue_ = blue_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.white_ = white_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.colorTemperature_ = colorTemperature_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.coldWhite_ = coldWhite_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.warmWhite_ = warmWhite_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.effect_ = effect_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse) {
        return mergeFrom((it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse other) {
      if (other == it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse.getDefaultInstance()) return this;
      if (other.getKey() != 0) {
        setKey(other.getKey());
      }
      if (other.getState() != false) {
        setState(other.getState());
      }
      if (other.getBrightness() != 0F) {
        setBrightness(other.getBrightness());
      }
      if (other.colorMode_ != 0) {
        setColorModeValue(other.getColorModeValue());
      }
      if (other.getColorBrightness() != 0F) {
        setColorBrightness(other.getColorBrightness());
      }
      if (other.getRed() != 0F) {
        setRed(other.getRed());
      }
      if (other.getGreen() != 0F) {
        setGreen(other.getGreen());
      }
      if (other.getBlue() != 0F) {
        setBlue(other.getBlue());
      }
      if (other.getWhite() != 0F) {
        setWhite(other.getWhite());
      }
      if (other.getColorTemperature() != 0F) {
        setColorTemperature(other.getColorTemperature());
      }
      if (other.getColdWhite() != 0F) {
        setColdWhite(other.getColdWhite());
      }
      if (other.getWarmWhite() != 0F) {
        setWarmWhite(other.getWarmWhite());
      }
      if (!other.getEffect().isEmpty()) {
        effect_ = other.effect_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              key_ = input.readFixed32();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 16: {
              state_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 29: {
              brightness_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 37: {
              red_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 37
            case 45: {
              green_ = input.readFloat();
              bitField0_ |= 0x00000040;
              break;
            } // case 45
            case 53: {
              blue_ = input.readFloat();
              bitField0_ |= 0x00000080;
              break;
            } // case 53
            case 61: {
              white_ = input.readFloat();
              bitField0_ |= 0x00000100;
              break;
            } // case 61
            case 69: {
              colorTemperature_ = input.readFloat();
              bitField0_ |= 0x00000200;
              break;
            } // case 69
            case 74: {
              effect_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 74
            case 85: {
              colorBrightness_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 85
            case 88: {
              colorMode_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 88
            case 101: {
              coldWhite_ = input.readFloat();
              bitField0_ |= 0x00000400;
              break;
            } // case 101
            case 109: {
              warmWhite_ = input.readFloat();
              bitField0_ |= 0x00000800;
              break;
            } // case 109
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int key_ ;
    /**
     * <code>fixed32 key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public int getKey() {
      return key_;
    }
    /**
     * <code>fixed32 key = 1;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(int value) {
      
      key_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>fixed32 key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      bitField0_ = (bitField0_ & ~0x00000001);
      key_ = 0;
      onChanged();
      return this;
    }

    private boolean state_ ;
    /**
     * <code>bool state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public boolean getState() {
      return state_;
    }
    /**
     * <code>bool state = 2;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(boolean value) {
      
      state_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000002);
      state_ = false;
      onChanged();
      return this;
    }

    private float brightness_ ;
    /**
     * <code>float brightness = 3;</code>
     * @return The brightness.
     */
    @java.lang.Override
    public float getBrightness() {
      return brightness_;
    }
    /**
     * <code>float brightness = 3;</code>
     * @param value The brightness to set.
     * @return This builder for chaining.
     */
    public Builder setBrightness(float value) {
      
      brightness_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float brightness = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrightness() {
      bitField0_ = (bitField0_ & ~0x00000004);
      brightness_ = 0F;
      onChanged();
      return this;
    }

    private int colorMode_ = 0;
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.ColorMode color_mode = 11;</code>
     * @return The enum numeric value on the wire for colorMode.
     */
    @java.lang.Override public int getColorModeValue() {
      return colorMode_;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.ColorMode color_mode = 11;</code>
     * @param value The enum numeric value on the wire for colorMode to set.
     * @return This builder for chaining.
     */
    public Builder setColorModeValue(int value) {
      colorMode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.ColorMode color_mode = 11;</code>
     * @return The colorMode.
     */
    @java.lang.Override
    public it.achdjian.sottovasoluminoso.protobuf.java.ColorMode getColorMode() {
      it.achdjian.sottovasoluminoso.protobuf.java.ColorMode result = it.achdjian.sottovasoluminoso.protobuf.java.ColorMode.forNumber(colorMode_);
      return result == null ? it.achdjian.sottovasoluminoso.protobuf.java.ColorMode.UNRECOGNIZED : result;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.ColorMode color_mode = 11;</code>
     * @param value The colorMode to set.
     * @return This builder for chaining.
     */
    public Builder setColorMode(it.achdjian.sottovasoluminoso.protobuf.java.ColorMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      colorMode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.ColorMode color_mode = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorMode() {
      bitField0_ = (bitField0_ & ~0x00000008);
      colorMode_ = 0;
      onChanged();
      return this;
    }

    private float colorBrightness_ ;
    /**
     * <code>float color_brightness = 10;</code>
     * @return The colorBrightness.
     */
    @java.lang.Override
    public float getColorBrightness() {
      return colorBrightness_;
    }
    /**
     * <code>float color_brightness = 10;</code>
     * @param value The colorBrightness to set.
     * @return This builder for chaining.
     */
    public Builder setColorBrightness(float value) {
      
      colorBrightness_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>float color_brightness = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorBrightness() {
      bitField0_ = (bitField0_ & ~0x00000010);
      colorBrightness_ = 0F;
      onChanged();
      return this;
    }

    private float red_ ;
    /**
     * <code>float red = 4;</code>
     * @return The red.
     */
    @java.lang.Override
    public float getRed() {
      return red_;
    }
    /**
     * <code>float red = 4;</code>
     * @param value The red to set.
     * @return This builder for chaining.
     */
    public Builder setRed(float value) {
      
      red_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>float red = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRed() {
      bitField0_ = (bitField0_ & ~0x00000020);
      red_ = 0F;
      onChanged();
      return this;
    }

    private float green_ ;
    /**
     * <code>float green = 5;</code>
     * @return The green.
     */
    @java.lang.Override
    public float getGreen() {
      return green_;
    }
    /**
     * <code>float green = 5;</code>
     * @param value The green to set.
     * @return This builder for chaining.
     */
    public Builder setGreen(float value) {
      
      green_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>float green = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGreen() {
      bitField0_ = (bitField0_ & ~0x00000040);
      green_ = 0F;
      onChanged();
      return this;
    }

    private float blue_ ;
    /**
     * <code>float blue = 6;</code>
     * @return The blue.
     */
    @java.lang.Override
    public float getBlue() {
      return blue_;
    }
    /**
     * <code>float blue = 6;</code>
     * @param value The blue to set.
     * @return This builder for chaining.
     */
    public Builder setBlue(float value) {
      
      blue_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>float blue = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlue() {
      bitField0_ = (bitField0_ & ~0x00000080);
      blue_ = 0F;
      onChanged();
      return this;
    }

    private float white_ ;
    /**
     * <code>float white = 7;</code>
     * @return The white.
     */
    @java.lang.Override
    public float getWhite() {
      return white_;
    }
    /**
     * <code>float white = 7;</code>
     * @param value The white to set.
     * @return This builder for chaining.
     */
    public Builder setWhite(float value) {
      
      white_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>float white = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWhite() {
      bitField0_ = (bitField0_ & ~0x00000100);
      white_ = 0F;
      onChanged();
      return this;
    }

    private float colorTemperature_ ;
    /**
     * <code>float color_temperature = 8;</code>
     * @return The colorTemperature.
     */
    @java.lang.Override
    public float getColorTemperature() {
      return colorTemperature_;
    }
    /**
     * <code>float color_temperature = 8;</code>
     * @param value The colorTemperature to set.
     * @return This builder for chaining.
     */
    public Builder setColorTemperature(float value) {
      
      colorTemperature_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>float color_temperature = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorTemperature() {
      bitField0_ = (bitField0_ & ~0x00000200);
      colorTemperature_ = 0F;
      onChanged();
      return this;
    }

    private float coldWhite_ ;
    /**
     * <code>float cold_white = 12;</code>
     * @return The coldWhite.
     */
    @java.lang.Override
    public float getColdWhite() {
      return coldWhite_;
    }
    /**
     * <code>float cold_white = 12;</code>
     * @param value The coldWhite to set.
     * @return This builder for chaining.
     */
    public Builder setColdWhite(float value) {
      
      coldWhite_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>float cold_white = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearColdWhite() {
      bitField0_ = (bitField0_ & ~0x00000400);
      coldWhite_ = 0F;
      onChanged();
      return this;
    }

    private float warmWhite_ ;
    /**
     * <code>float warm_white = 13;</code>
     * @return The warmWhite.
     */
    @java.lang.Override
    public float getWarmWhite() {
      return warmWhite_;
    }
    /**
     * <code>float warm_white = 13;</code>
     * @param value The warmWhite to set.
     * @return This builder for chaining.
     */
    public Builder setWarmWhite(float value) {
      
      warmWhite_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>float warm_white = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearWarmWhite() {
      bitField0_ = (bitField0_ & ~0x00000800);
      warmWhite_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object effect_ = "";
    /**
     * <code>string effect = 9;</code>
     * @return The effect.
     */
    public java.lang.String getEffect() {
      java.lang.Object ref = effect_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        effect_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string effect = 9;</code>
     * @return The bytes for effect.
     */
    public com.google.protobuf.ByteString
        getEffectBytes() {
      java.lang.Object ref = effect_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        effect_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string effect = 9;</code>
     * @param value The effect to set.
     * @return This builder for chaining.
     */
    public Builder setEffect(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      effect_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string effect = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearEffect() {
      effect_ = getDefaultInstance().getEffect();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string effect = 9;</code>
     * @param value The bytes for effect to set.
     * @return This builder for chaining.
     */
    public Builder setEffectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      effect_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse)
  }

  // @@protoc_insertion_point(class_scope:it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse)
  private static final it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse();
  }

  public static it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LightStateResponse>
      PARSER = new com.google.protobuf.AbstractParser<LightStateResponse>() {
    @java.lang.Override
    public LightStateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LightStateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LightStateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

