// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.sottovasoluminoso.protobuf.java;

public interface LightStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.achdjian.sottovasoluminoso.protobuf.java.LightStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed32 key = 1;</code>
   * @return The key.
   */
  int getKey();

  /**
   * <code>bool state = 2;</code>
   * @return The state.
   */
  boolean getState();

  /**
   * <code>float brightness = 3;</code>
   * @return The brightness.
   */
  float getBrightness();

  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.ColorMode color_mode = 11;</code>
   * @return The enum numeric value on the wire for colorMode.
   */
  int getColorModeValue();
  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.ColorMode color_mode = 11;</code>
   * @return The colorMode.
   */
  it.achdjian.sottovasoluminoso.protobuf.java.ColorMode getColorMode();

  /**
   * <code>float color_brightness = 10;</code>
   * @return The colorBrightness.
   */
  float getColorBrightness();

  /**
   * <code>float red = 4;</code>
   * @return The red.
   */
  float getRed();

  /**
   * <code>float green = 5;</code>
   * @return The green.
   */
  float getGreen();

  /**
   * <code>float blue = 6;</code>
   * @return The blue.
   */
  float getBlue();

  /**
   * <code>float white = 7;</code>
   * @return The white.
   */
  float getWhite();

  /**
   * <code>float color_temperature = 8;</code>
   * @return The colorTemperature.
   */
  float getColorTemperature();

  /**
   * <code>float cold_white = 12;</code>
   * @return The coldWhite.
   */
  float getColdWhite();

  /**
   * <code>float warm_white = 13;</code>
   * @return The warmWhite.
   */
  float getWarmWhite();

  /**
   * <code>string effect = 9;</code>
   * @return The effect.
   */
  java.lang.String getEffect();
  /**
   * <code>string effect = 9;</code>
   * @return The bytes for effect.
   */
  com.google.protobuf.ByteString
      getEffectBytes();
}
