//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

package it.achdjian.sottovasoluminoso.protobuf.java;

@kotlin.jvm.JvmName("-initializemediaPlayerStateResponse")
public inline fun mediaPlayerStateResponse(block: it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponseKt.Dsl.() -> kotlin.Unit): it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponse =
  it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponseKt.Dsl._create(it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponse.newBuilder()).apply { block() }._build()
public object MediaPlayerStateResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponse = _builder.build()

    /**
     * <code>fixed32 key = 1;</code>
     */
    public var key: kotlin.Int
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <code>fixed32 key = 1;</code>
     */
    public fun clearKey() {
      _builder.clearKey()
    }

    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerState state = 2;</code>
     */
    public var state: it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerState
      @JvmName("getState")
      get() = _builder.getState()
      @JvmName("setState")
      set(value) {
        _builder.setState(value)
      }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerState state = 2;</code>
     */
    public fun clearState() {
      _builder.clearState()
    }

    /**
     * <code>float volume = 3;</code>
     */
    public var volume: kotlin.Float
      @JvmName("getVolume")
      get() = _builder.getVolume()
      @JvmName("setVolume")
      set(value) {
        _builder.setVolume(value)
      }
    /**
     * <code>float volume = 3;</code>
     */
    public fun clearVolume() {
      _builder.clearVolume()
    }

    /**
     * <code>bool muted = 4;</code>
     */
    public var muted: kotlin.Boolean
      @JvmName("getMuted")
      get() = _builder.getMuted()
      @JvmName("setMuted")
      set(value) {
        _builder.setMuted(value)
      }
    /**
     * <code>bool muted = 4;</code>
     */
    public fun clearMuted() {
      _builder.clearMuted()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponse.copy(block: it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponseKt.Dsl.() -> kotlin.Unit): it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponse =
  it.achdjian.sottovasoluminoso.protobuf.java.MediaPlayerStateResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

