// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api_options.proto

package it.achdjian.saucer.luminous.protobuf;

public final class ApiOptions {
  private ApiOptions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(it.achdjian.saucer.luminous.protobuf.ApiOptions.needsSetupConnection);
    registry.add(it.achdjian.saucer.luminous.protobuf.ApiOptions.needsAuthentication);
    registry.add(it.achdjian.saucer.luminous.protobuf.ApiOptions.id);
    registry.add(it.achdjian.saucer.luminous.protobuf.ApiOptions.source);
    registry.add(it.achdjian.saucer.luminous.protobuf.ApiOptions.ifdef);
    registry.add(it.achdjian.saucer.luminous.protobuf.ApiOptions.log);
    registry.add(it.achdjian.saucer.luminous.protobuf.ApiOptions.noDelay);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code it.achdjian.sottovasoluminoso.protobuf.java.APISourceType}
   */
  public enum APISourceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SOURCE_BOTH = 0;</code>
     */
    SOURCE_BOTH(0),
    /**
     * <code>SOURCE_SERVER = 1;</code>
     */
    SOURCE_SERVER(1),
    /**
     * <code>SOURCE_CLIENT = 2;</code>
     */
    SOURCE_CLIENT(2),
    ;

    /**
     * <code>SOURCE_BOTH = 0;</code>
     */
    public static final int SOURCE_BOTH_VALUE = 0;
    /**
     * <code>SOURCE_SERVER = 1;</code>
     */
    public static final int SOURCE_SERVER_VALUE = 1;
    /**
     * <code>SOURCE_CLIENT = 2;</code>
     */
    public static final int SOURCE_CLIENT_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static APISourceType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static APISourceType forNumber(int value) {
      switch (value) {
        case 0: return SOURCE_BOTH;
        case 1: return SOURCE_SERVER;
        case 2: return SOURCE_CLIENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<APISourceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        APISourceType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<APISourceType>() {
            public APISourceType findValueByNumber(int number) {
              return APISourceType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return it.achdjian.saucer.luminous.protobuf.ApiOptions.getDescriptor().getEnumTypes().get(0);
    }

    private static final APISourceType[] VALUES = values();

    public static APISourceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private APISourceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:it.achdjian.sottovasoluminoso.protobuf.java.APISourceType)
  }

  public interface VoidOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.achdjian.sottovasoluminoso.protobuf.java.Void)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.Void}
   */
  public static final class Void extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:it.achdjian.sottovasoluminoso.protobuf.java.Void)
      VoidOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Void.newBuilder() to construct.
    private Void(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Void() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Void();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.achdjian.saucer.luminous.protobuf.ApiOptions.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_Void_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.achdjian.saucer.luminous.protobuf.ApiOptions.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_Void_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.achdjian.saucer.luminous.protobuf.ApiOptions.Void.class, it.achdjian.saucer.luminous.protobuf.ApiOptions.Void.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.achdjian.saucer.luminous.protobuf.ApiOptions.Void)) {
        return super.equals(obj);
      }
      it.achdjian.saucer.luminous.protobuf.ApiOptions.Void other = (it.achdjian.saucer.luminous.protobuf.ApiOptions.Void) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.achdjian.saucer.luminous.protobuf.ApiOptions.Void prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.Void}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.achdjian.sottovasoluminoso.protobuf.java.Void)
        it.achdjian.saucer.luminous.protobuf.ApiOptions.VoidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.achdjian.saucer.luminous.protobuf.ApiOptions.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_Void_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.achdjian.saucer.luminous.protobuf.ApiOptions.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_Void_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.achdjian.saucer.luminous.protobuf.ApiOptions.Void.class, it.achdjian.saucer.luminous.protobuf.ApiOptions.Void.Builder.class);
      }

      // Construct using it.achdjian.saucer.luminous.protobuf.ApiOptions.Void.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.achdjian.saucer.luminous.protobuf.ApiOptions.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_Void_descriptor;
      }

      @java.lang.Override
      public it.achdjian.saucer.luminous.protobuf.ApiOptions.Void getDefaultInstanceForType() {
        return it.achdjian.saucer.luminous.protobuf.ApiOptions.Void.getDefaultInstance();
      }

      @java.lang.Override
      public it.achdjian.saucer.luminous.protobuf.ApiOptions.Void build() {
        it.achdjian.saucer.luminous.protobuf.ApiOptions.Void result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public it.achdjian.saucer.luminous.protobuf.ApiOptions.Void buildPartial() {
        it.achdjian.saucer.luminous.protobuf.ApiOptions.Void result = new it.achdjian.saucer.luminous.protobuf.ApiOptions.Void(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.achdjian.saucer.luminous.protobuf.ApiOptions.Void) {
          return mergeFrom((it.achdjian.saucer.luminous.protobuf.ApiOptions.Void)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.achdjian.saucer.luminous.protobuf.ApiOptions.Void other) {
        if (other == it.achdjian.saucer.luminous.protobuf.ApiOptions.Void.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:it.achdjian.sottovasoluminoso.protobuf.java.Void)
    }

    // @@protoc_insertion_point(class_scope:it.achdjian.sottovasoluminoso.protobuf.java.Void)
    private static final it.achdjian.saucer.luminous.protobuf.ApiOptions.Void DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.achdjian.saucer.luminous.protobuf.ApiOptions.Void();
    }

    public static it.achdjian.saucer.luminous.protobuf.ApiOptions.Void getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Void>
        PARSER = new com.google.protobuf.AbstractParser<Void>() {
      @java.lang.Override
      public Void parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Void> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Void> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.ApiOptions.Void getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NEEDS_SETUP_CONNECTION_FIELD_NUMBER = 1038;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Boolean> needsSetupConnection = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int NEEDS_AUTHENTICATION_FIELD_NUMBER = 1039;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Boolean> needsAuthentication = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int ID_FIELD_NUMBER = 1036;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Integer> id = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int SOURCE_FIELD_NUMBER = 1037;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      it.achdjian.saucer.luminous.protobuf.ApiOptions.APISourceType> source = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        it.achdjian.saucer.luminous.protobuf.ApiOptions.APISourceType.class,
        null);
  public static final int IFDEF_FIELD_NUMBER = 1038;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> ifdef = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int LOG_FIELD_NUMBER = 1039;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> log = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int NO_DELAY_FIELD_NUMBER = 1040;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> noDelay = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_achdjian_sottovasoluminoso_protobuf_java_Void_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_achdjian_sottovasoluminoso_protobuf_java_Void_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021api_options.proto\022+it.achdjian.sottova" +
      "soluminoso.protobuf.java\032 google/protobu" +
      "f/descriptor.proto\"\006\n\004Void*F\n\rAPISourceT" +
      "ype\022\017\n\013SOURCE_BOTH\020\000\022\021\n\rSOURCE_SERVER\020\001\022" +
      "\021\n\rSOURCE_CLIENT\020\002:E\n\026needs_setup_connec" +
      "tion\022\036.google.protobuf.MethodOptions\030\216\010 " +
      "\001(\010:\004true:C\n\024needs_authentication\022\036.goog" +
      "le.protobuf.MethodOptions\030\217\010 \001(\010:\004true:/" +
      "\n\002id\022\037.google.protobuf.MessageOptions\030\214\010" +
      " \001(\r:\0010:y\n\006source\022\037.google.protobuf.Mess" +
      "ageOptions\030\215\010 \001(\0162:.it.achdjian.sottovas" +
      "oluminoso.protobuf.java.APISourceType:\013S" +
      "OURCE_BOTH:/\n\005ifdef\022\037.google.protobuf.Me" +
      "ssageOptions\030\216\010 \001(\t:3\n\003log\022\037.google.prot" +
      "obuf.MessageOptions\030\217\010 \001(\010:\004true:9\n\010no_d" +
      "elay\022\037.google.protobuf.MessageOptions\030\220\010" +
      " \001(\010:\005falseB&\n$it.achdjian.saucer.lumino" +
      "us.protobuf"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_it_achdjian_sottovasoluminoso_protobuf_java_Void_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_it_achdjian_sottovasoluminoso_protobuf_java_Void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_achdjian_sottovasoluminoso_protobuf_java_Void_descriptor,
        new java.lang.String[] { });
    needsSetupConnection.internalInit(descriptor.getExtensions().get(0));
    needsAuthentication.internalInit(descriptor.getExtensions().get(1));
    id.internalInit(descriptor.getExtensions().get(2));
    source.internalInit(descriptor.getExtensions().get(3));
    ifdef.internalInit(descriptor.getExtensions().get(4));
    log.internalInit(descriptor.getExtensions().get(5));
    noDelay.internalInit(descriptor.getExtensions().get(6));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
