// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.saucer.luminous.protobuf;

/**
 * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.BluetoothDeviceConnectionResponse}
 */
public final class BluetoothDeviceConnectionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothDeviceConnectionResponse)
    BluetoothDeviceConnectionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BluetoothDeviceConnectionResponse.newBuilder() to construct.
  private BluetoothDeviceConnectionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BluetoothDeviceConnectionResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BluetoothDeviceConnectionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothDeviceConnectionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothDeviceConnectionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse.class, it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse.Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  private long address_ = 0L;
  /**
   * <code>uint64 address = 1;</code>
   * @return The address.
   */
  @java.lang.Override
  public long getAddress() {
    return address_;
  }

  public static final int CONNECTED_FIELD_NUMBER = 2;
  private boolean connected_ = false;
  /**
   * <code>bool connected = 2;</code>
   * @return The connected.
   */
  @java.lang.Override
  public boolean getConnected() {
    return connected_;
  }

  public static final int MTU_FIELD_NUMBER = 3;
  private int mtu_ = 0;
  /**
   * <code>uint32 mtu = 3;</code>
   * @return The mtu.
   */
  @java.lang.Override
  public int getMtu() {
    return mtu_;
  }

  public static final int ERROR_FIELD_NUMBER = 4;
  private int error_ = 0;
  /**
   * <code>int32 error = 4;</code>
   * @return The error.
   */
  @java.lang.Override
  public int getError() {
    return error_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (address_ != 0L) {
      output.writeUInt64(1, address_);
    }
    if (connected_ != false) {
      output.writeBool(2, connected_);
    }
    if (mtu_ != 0) {
      output.writeUInt32(3, mtu_);
    }
    if (error_ != 0) {
      output.writeInt32(4, error_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (address_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, address_);
    }
    if (connected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, connected_);
    }
    if (mtu_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, mtu_);
    }
    if (error_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, error_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse)) {
      return super.equals(obj);
    }
    it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse other = (it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse) obj;

    if (getAddress()
        != other.getAddress()) return false;
    if (getConnected()
        != other.getConnected()) return false;
    if (getMtu()
        != other.getMtu()) return false;
    if (getError()
        != other.getError()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAddress());
    hash = (37 * hash) + CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getConnected());
    hash = (37 * hash) + MTU_FIELD_NUMBER;
    hash = (53 * hash) + getMtu();
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.BluetoothDeviceConnectionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothDeviceConnectionResponse)
      it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothDeviceConnectionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothDeviceConnectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse.class, it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse.Builder.class);
    }

    // Construct using it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      address_ = 0L;
      connected_ = false;
      mtu_ = 0;
      error_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothDeviceConnectionResponse_descriptor;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse getDefaultInstanceForType() {
      return it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse build() {
      it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse buildPartial() {
      it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse result = new it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.address_ = address_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.connected_ = connected_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mtu_ = mtu_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.error_ = error_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse) {
        return mergeFrom((it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse other) {
      if (other == it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse.getDefaultInstance()) return this;
      if (other.getAddress() != 0L) {
        setAddress(other.getAddress());
      }
      if (other.getConnected() != false) {
        setConnected(other.getConnected());
      }
      if (other.getMtu() != 0) {
        setMtu(other.getMtu());
      }
      if (other.getError() != 0) {
        setError(other.getError());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              address_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              connected_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              mtu_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              error_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long address_ ;
    /**
     * <code>uint64 address = 1;</code>
     * @return The address.
     */
    @java.lang.Override
    public long getAddress() {
      return address_;
    }
    /**
     * <code>uint64 address = 1;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(long value) {
      
      address_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 address = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000001);
      address_ = 0L;
      onChanged();
      return this;
    }

    private boolean connected_ ;
    /**
     * <code>bool connected = 2;</code>
     * @return The connected.
     */
    @java.lang.Override
    public boolean getConnected() {
      return connected_;
    }
    /**
     * <code>bool connected = 2;</code>
     * @param value The connected to set.
     * @return This builder for chaining.
     */
    public Builder setConnected(boolean value) {
      
      connected_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool connected = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnected() {
      bitField0_ = (bitField0_ & ~0x00000002);
      connected_ = false;
      onChanged();
      return this;
    }

    private int mtu_ ;
    /**
     * <code>uint32 mtu = 3;</code>
     * @return The mtu.
     */
    @java.lang.Override
    public int getMtu() {
      return mtu_;
    }
    /**
     * <code>uint32 mtu = 3;</code>
     * @param value The mtu to set.
     * @return This builder for chaining.
     */
    public Builder setMtu(int value) {
      
      mtu_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 mtu = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMtu() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mtu_ = 0;
      onChanged();
      return this;
    }

    private int error_ ;
    /**
     * <code>int32 error = 4;</code>
     * @return The error.
     */
    @java.lang.Override
    public int getError() {
      return error_;
    }
    /**
     * <code>int32 error = 4;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(int value) {
      
      error_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 error = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000008);
      error_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothDeviceConnectionResponse)
  }

  // @@protoc_insertion_point(class_scope:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothDeviceConnectionResponse)
  private static final it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse();
  }

  public static it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BluetoothDeviceConnectionResponse>
      PARSER = new com.google.protobuf.AbstractParser<BluetoothDeviceConnectionResponse>() {
    @java.lang.Override
    public BluetoothDeviceConnectionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BluetoothDeviceConnectionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BluetoothDeviceConnectionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.BluetoothDeviceConnectionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

