// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.saucer.luminous.protobuf;

/**
 * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.BluetoothLEAdvertisementResponse}
 */
public final class BluetoothLEAdvertisementResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothLEAdvertisementResponse)
    BluetoothLEAdvertisementResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BluetoothLEAdvertisementResponse.newBuilder() to construct.
  private BluetoothLEAdvertisementResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BluetoothLEAdvertisementResponse() {
    name_ = "";
    serviceUuids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    serviceData_ = java.util.Collections.emptyList();
    manufacturerData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BluetoothLEAdvertisementResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothLEAdvertisementResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothLEAdvertisementResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse.class, it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse.Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  private long address_ = 0L;
  /**
   * <code>uint64 address = 1;</code>
   * @return The address.
   */
  @java.lang.Override
  public long getAddress() {
    return address_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RSSI_FIELD_NUMBER = 3;
  private int rssi_ = 0;
  /**
   * <code>sint32 rssi = 3;</code>
   * @return The rssi.
   */
  @java.lang.Override
  public int getRssi() {
    return rssi_;
  }

  public static final int SERVICE_UUIDS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList serviceUuids_;
  /**
   * <code>repeated string service_uuids = 4;</code>
   * @return A list containing the serviceUuids.
   */
  public com.google.protobuf.ProtocolStringList
      getServiceUuidsList() {
    return serviceUuids_;
  }
  /**
   * <code>repeated string service_uuids = 4;</code>
   * @return The count of serviceUuids.
   */
  public int getServiceUuidsCount() {
    return serviceUuids_.size();
  }
  /**
   * <code>repeated string service_uuids = 4;</code>
   * @param index The index of the element to return.
   * @return The serviceUuids at the given index.
   */
  public java.lang.String getServiceUuids(int index) {
    return serviceUuids_.get(index);
  }
  /**
   * <code>repeated string service_uuids = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the serviceUuids at the given index.
   */
  public com.google.protobuf.ByteString
      getServiceUuidsBytes(int index) {
    return serviceUuids_.getByteString(index);
  }

  public static final int SERVICE_DATA_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData> serviceData_;
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
   */
  @java.lang.Override
  public java.util.List<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData> getServiceDataList() {
    return serviceData_;
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder> 
      getServiceDataOrBuilderList() {
    return serviceData_;
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
   */
  @java.lang.Override
  public int getServiceDataCount() {
    return serviceData_.size();
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
   */
  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.BluetoothServiceData getServiceData(int index) {
    return serviceData_.get(index);
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
   */
  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder getServiceDataOrBuilder(
      int index) {
    return serviceData_.get(index);
  }

  public static final int MANUFACTURER_DATA_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData> manufacturerData_;
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
   */
  @java.lang.Override
  public java.util.List<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData> getManufacturerDataList() {
    return manufacturerData_;
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder> 
      getManufacturerDataOrBuilderList() {
    return manufacturerData_;
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
   */
  @java.lang.Override
  public int getManufacturerDataCount() {
    return manufacturerData_.size();
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
   */
  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.BluetoothServiceData getManufacturerData(int index) {
    return manufacturerData_.get(index);
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
   */
  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder getManufacturerDataOrBuilder(
      int index) {
    return manufacturerData_.get(index);
  }

  public static final int ADDRESS_TYPE_FIELD_NUMBER = 7;
  private int addressType_ = 0;
  /**
   * <code>uint32 address_type = 7;</code>
   * @return The addressType.
   */
  @java.lang.Override
  public int getAddressType() {
    return addressType_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (address_ != 0L) {
      output.writeUInt64(1, address_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (rssi_ != 0) {
      output.writeSInt32(3, rssi_);
    }
    for (int i = 0; i < serviceUuids_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serviceUuids_.getRaw(i));
    }
    for (int i = 0; i < serviceData_.size(); i++) {
      output.writeMessage(5, serviceData_.get(i));
    }
    for (int i = 0; i < manufacturerData_.size(); i++) {
      output.writeMessage(6, manufacturerData_.get(i));
    }
    if (addressType_ != 0) {
      output.writeUInt32(7, addressType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (address_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, address_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (rssi_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(3, rssi_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < serviceUuids_.size(); i++) {
        dataSize += computeStringSizeNoTag(serviceUuids_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getServiceUuidsList().size();
    }
    for (int i = 0; i < serviceData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, serviceData_.get(i));
    }
    for (int i = 0; i < manufacturerData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, manufacturerData_.get(i));
    }
    if (addressType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, addressType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse)) {
      return super.equals(obj);
    }
    it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse other = (it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse) obj;

    if (getAddress()
        != other.getAddress()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getRssi()
        != other.getRssi()) return false;
    if (!getServiceUuidsList()
        .equals(other.getServiceUuidsList())) return false;
    if (!getServiceDataList()
        .equals(other.getServiceDataList())) return false;
    if (!getManufacturerDataList()
        .equals(other.getManufacturerDataList())) return false;
    if (getAddressType()
        != other.getAddressType()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAddress());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + RSSI_FIELD_NUMBER;
    hash = (53 * hash) + getRssi();
    if (getServiceUuidsCount() > 0) {
      hash = (37 * hash) + SERVICE_UUIDS_FIELD_NUMBER;
      hash = (53 * hash) + getServiceUuidsList().hashCode();
    }
    if (getServiceDataCount() > 0) {
      hash = (37 * hash) + SERVICE_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getServiceDataList().hashCode();
    }
    if (getManufacturerDataCount() > 0) {
      hash = (37 * hash) + MANUFACTURER_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturerDataList().hashCode();
    }
    hash = (37 * hash) + ADDRESS_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAddressType();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.BluetoothLEAdvertisementResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothLEAdvertisementResponse)
      it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothLEAdvertisementResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothLEAdvertisementResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse.class, it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse.Builder.class);
    }

    // Construct using it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      address_ = 0L;
      name_ = "";
      rssi_ = 0;
      serviceUuids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (serviceDataBuilder_ == null) {
        serviceData_ = java.util.Collections.emptyList();
      } else {
        serviceData_ = null;
        serviceDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (manufacturerDataBuilder_ == null) {
        manufacturerData_ = java.util.Collections.emptyList();
      } else {
        manufacturerData_ = null;
        manufacturerDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      addressType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_BluetoothLEAdvertisementResponse_descriptor;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse getDefaultInstanceForType() {
      return it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse.getDefaultInstance();
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse build() {
      it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse buildPartial() {
      it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse result = new it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse result) {
      if (((bitField0_ & 0x00000008) != 0)) {
        serviceUuids_ = serviceUuids_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.serviceUuids_ = serviceUuids_;
      if (serviceDataBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          serviceData_ = java.util.Collections.unmodifiableList(serviceData_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.serviceData_ = serviceData_;
      } else {
        result.serviceData_ = serviceDataBuilder_.build();
      }
      if (manufacturerDataBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          manufacturerData_ = java.util.Collections.unmodifiableList(manufacturerData_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.manufacturerData_ = manufacturerData_;
      } else {
        result.manufacturerData_ = manufacturerDataBuilder_.build();
      }
    }

    private void buildPartial0(it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.address_ = address_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rssi_ = rssi_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.addressType_ = addressType_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse) {
        return mergeFrom((it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse other) {
      if (other == it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse.getDefaultInstance()) return this;
      if (other.getAddress() != 0L) {
        setAddress(other.getAddress());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getRssi() != 0) {
        setRssi(other.getRssi());
      }
      if (!other.serviceUuids_.isEmpty()) {
        if (serviceUuids_.isEmpty()) {
          serviceUuids_ = other.serviceUuids_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureServiceUuidsIsMutable();
          serviceUuids_.addAll(other.serviceUuids_);
        }
        onChanged();
      }
      if (serviceDataBuilder_ == null) {
        if (!other.serviceData_.isEmpty()) {
          if (serviceData_.isEmpty()) {
            serviceData_ = other.serviceData_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureServiceDataIsMutable();
            serviceData_.addAll(other.serviceData_);
          }
          onChanged();
        }
      } else {
        if (!other.serviceData_.isEmpty()) {
          if (serviceDataBuilder_.isEmpty()) {
            serviceDataBuilder_.dispose();
            serviceDataBuilder_ = null;
            serviceData_ = other.serviceData_;
            bitField0_ = (bitField0_ & ~0x00000010);
            serviceDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getServiceDataFieldBuilder() : null;
          } else {
            serviceDataBuilder_.addAllMessages(other.serviceData_);
          }
        }
      }
      if (manufacturerDataBuilder_ == null) {
        if (!other.manufacturerData_.isEmpty()) {
          if (manufacturerData_.isEmpty()) {
            manufacturerData_ = other.manufacturerData_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureManufacturerDataIsMutable();
            manufacturerData_.addAll(other.manufacturerData_);
          }
          onChanged();
        }
      } else {
        if (!other.manufacturerData_.isEmpty()) {
          if (manufacturerDataBuilder_.isEmpty()) {
            manufacturerDataBuilder_.dispose();
            manufacturerDataBuilder_ = null;
            manufacturerData_ = other.manufacturerData_;
            bitField0_ = (bitField0_ & ~0x00000020);
            manufacturerDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getManufacturerDataFieldBuilder() : null;
          } else {
            manufacturerDataBuilder_.addAllMessages(other.manufacturerData_);
          }
        }
      }
      if (other.getAddressType() != 0) {
        setAddressType(other.getAddressType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              address_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              rssi_ = input.readSInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureServiceUuidsIsMutable();
              serviceUuids_.add(s);
              break;
            } // case 34
            case 42: {
              it.achdjian.saucer.luminous.protobuf.BluetoothServiceData m =
                  input.readMessage(
                      it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.parser(),
                      extensionRegistry);
              if (serviceDataBuilder_ == null) {
                ensureServiceDataIsMutable();
                serviceData_.add(m);
              } else {
                serviceDataBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              it.achdjian.saucer.luminous.protobuf.BluetoothServiceData m =
                  input.readMessage(
                      it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.parser(),
                      extensionRegistry);
              if (manufacturerDataBuilder_ == null) {
                ensureManufacturerDataIsMutable();
                manufacturerData_.add(m);
              } else {
                manufacturerDataBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 56: {
              addressType_ = input.readUInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long address_ ;
    /**
     * <code>uint64 address = 1;</code>
     * @return The address.
     */
    @java.lang.Override
    public long getAddress() {
      return address_;
    }
    /**
     * <code>uint64 address = 1;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(long value) {
      
      address_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 address = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000001);
      address_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int rssi_ ;
    /**
     * <code>sint32 rssi = 3;</code>
     * @return The rssi.
     */
    @java.lang.Override
    public int getRssi() {
      return rssi_;
    }
    /**
     * <code>sint32 rssi = 3;</code>
     * @param value The rssi to set.
     * @return This builder for chaining.
     */
    public Builder setRssi(int value) {
      
      rssi_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 rssi = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRssi() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rssi_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList serviceUuids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureServiceUuidsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        serviceUuids_ = new com.google.protobuf.LazyStringArrayList(serviceUuids_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string service_uuids = 4;</code>
     * @return A list containing the serviceUuids.
     */
    public com.google.protobuf.ProtocolStringList
        getServiceUuidsList() {
      return serviceUuids_.getUnmodifiableView();
    }
    /**
     * <code>repeated string service_uuids = 4;</code>
     * @return The count of serviceUuids.
     */
    public int getServiceUuidsCount() {
      return serviceUuids_.size();
    }
    /**
     * <code>repeated string service_uuids = 4;</code>
     * @param index The index of the element to return.
     * @return The serviceUuids at the given index.
     */
    public java.lang.String getServiceUuids(int index) {
      return serviceUuids_.get(index);
    }
    /**
     * <code>repeated string service_uuids = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the serviceUuids at the given index.
     */
    public com.google.protobuf.ByteString
        getServiceUuidsBytes(int index) {
      return serviceUuids_.getByteString(index);
    }
    /**
     * <code>repeated string service_uuids = 4;</code>
     * @param index The index to set the value at.
     * @param value The serviceUuids to set.
     * @return This builder for chaining.
     */
    public Builder setServiceUuids(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureServiceUuidsIsMutable();
      serviceUuids_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string service_uuids = 4;</code>
     * @param value The serviceUuids to add.
     * @return This builder for chaining.
     */
    public Builder addServiceUuids(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureServiceUuidsIsMutable();
      serviceUuids_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string service_uuids = 4;</code>
     * @param values The serviceUuids to add.
     * @return This builder for chaining.
     */
    public Builder addAllServiceUuids(
        java.lang.Iterable<java.lang.String> values) {
      ensureServiceUuidsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, serviceUuids_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string service_uuids = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceUuids() {
      serviceUuids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string service_uuids = 4;</code>
     * @param value The bytes of the serviceUuids to add.
     * @return This builder for chaining.
     */
    public Builder addServiceUuidsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureServiceUuidsIsMutable();
      serviceUuids_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData> serviceData_ =
      java.util.Collections.emptyList();
    private void ensureServiceDataIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        serviceData_ = new java.util.ArrayList<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData>(serviceData_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        it.achdjian.saucer.luminous.protobuf.BluetoothServiceData, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder, it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder> serviceDataBuilder_;

    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public java.util.List<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData> getServiceDataList() {
      if (serviceDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(serviceData_);
      } else {
        return serviceDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public int getServiceDataCount() {
      if (serviceDataBuilder_ == null) {
        return serviceData_.size();
      } else {
        return serviceDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.BluetoothServiceData getServiceData(int index) {
      if (serviceDataBuilder_ == null) {
        return serviceData_.get(index);
      } else {
        return serviceDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public Builder setServiceData(
        int index, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData value) {
      if (serviceDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceDataIsMutable();
        serviceData_.set(index, value);
        onChanged();
      } else {
        serviceDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public Builder setServiceData(
        int index, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder builderForValue) {
      if (serviceDataBuilder_ == null) {
        ensureServiceDataIsMutable();
        serviceData_.set(index, builderForValue.build());
        onChanged();
      } else {
        serviceDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public Builder addServiceData(it.achdjian.saucer.luminous.protobuf.BluetoothServiceData value) {
      if (serviceDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceDataIsMutable();
        serviceData_.add(value);
        onChanged();
      } else {
        serviceDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public Builder addServiceData(
        int index, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData value) {
      if (serviceDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceDataIsMutable();
        serviceData_.add(index, value);
        onChanged();
      } else {
        serviceDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public Builder addServiceData(
        it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder builderForValue) {
      if (serviceDataBuilder_ == null) {
        ensureServiceDataIsMutable();
        serviceData_.add(builderForValue.build());
        onChanged();
      } else {
        serviceDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public Builder addServiceData(
        int index, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder builderForValue) {
      if (serviceDataBuilder_ == null) {
        ensureServiceDataIsMutable();
        serviceData_.add(index, builderForValue.build());
        onChanged();
      } else {
        serviceDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public Builder addAllServiceData(
        java.lang.Iterable<? extends it.achdjian.saucer.luminous.protobuf.BluetoothServiceData> values) {
      if (serviceDataBuilder_ == null) {
        ensureServiceDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, serviceData_);
        onChanged();
      } else {
        serviceDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public Builder clearServiceData() {
      if (serviceDataBuilder_ == null) {
        serviceData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        serviceDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public Builder removeServiceData(int index) {
      if (serviceDataBuilder_ == null) {
        ensureServiceDataIsMutable();
        serviceData_.remove(index);
        onChanged();
      } else {
        serviceDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder getServiceDataBuilder(
        int index) {
      return getServiceDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder getServiceDataOrBuilder(
        int index) {
      if (serviceDataBuilder_ == null) {
        return serviceData_.get(index);  } else {
        return serviceDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public java.util.List<? extends it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder> 
         getServiceDataOrBuilderList() {
      if (serviceDataBuilder_ != null) {
        return serviceDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(serviceData_);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder addServiceDataBuilder() {
      return getServiceDataFieldBuilder().addBuilder(
          it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.getDefaultInstance());
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder addServiceDataBuilder(
        int index) {
      return getServiceDataFieldBuilder().addBuilder(
          index, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.getDefaultInstance());
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData service_data = 5;</code>
     */
    public java.util.List<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder> 
         getServiceDataBuilderList() {
      return getServiceDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        it.achdjian.saucer.luminous.protobuf.BluetoothServiceData, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder, it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder> 
        getServiceDataFieldBuilder() {
      if (serviceDataBuilder_ == null) {
        serviceDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            it.achdjian.saucer.luminous.protobuf.BluetoothServiceData, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder, it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder>(
                serviceData_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        serviceData_ = null;
      }
      return serviceDataBuilder_;
    }

    private java.util.List<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData> manufacturerData_ =
      java.util.Collections.emptyList();
    private void ensureManufacturerDataIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        manufacturerData_ = new java.util.ArrayList<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData>(manufacturerData_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        it.achdjian.saucer.luminous.protobuf.BluetoothServiceData, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder, it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder> manufacturerDataBuilder_;

    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public java.util.List<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData> getManufacturerDataList() {
      if (manufacturerDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(manufacturerData_);
      } else {
        return manufacturerDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public int getManufacturerDataCount() {
      if (manufacturerDataBuilder_ == null) {
        return manufacturerData_.size();
      } else {
        return manufacturerDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.BluetoothServiceData getManufacturerData(int index) {
      if (manufacturerDataBuilder_ == null) {
        return manufacturerData_.get(index);
      } else {
        return manufacturerDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public Builder setManufacturerData(
        int index, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData value) {
      if (manufacturerDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureManufacturerDataIsMutable();
        manufacturerData_.set(index, value);
        onChanged();
      } else {
        manufacturerDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public Builder setManufacturerData(
        int index, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder builderForValue) {
      if (manufacturerDataBuilder_ == null) {
        ensureManufacturerDataIsMutable();
        manufacturerData_.set(index, builderForValue.build());
        onChanged();
      } else {
        manufacturerDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public Builder addManufacturerData(it.achdjian.saucer.luminous.protobuf.BluetoothServiceData value) {
      if (manufacturerDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureManufacturerDataIsMutable();
        manufacturerData_.add(value);
        onChanged();
      } else {
        manufacturerDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public Builder addManufacturerData(
        int index, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData value) {
      if (manufacturerDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureManufacturerDataIsMutable();
        manufacturerData_.add(index, value);
        onChanged();
      } else {
        manufacturerDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public Builder addManufacturerData(
        it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder builderForValue) {
      if (manufacturerDataBuilder_ == null) {
        ensureManufacturerDataIsMutable();
        manufacturerData_.add(builderForValue.build());
        onChanged();
      } else {
        manufacturerDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public Builder addManufacturerData(
        int index, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder builderForValue) {
      if (manufacturerDataBuilder_ == null) {
        ensureManufacturerDataIsMutable();
        manufacturerData_.add(index, builderForValue.build());
        onChanged();
      } else {
        manufacturerDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public Builder addAllManufacturerData(
        java.lang.Iterable<? extends it.achdjian.saucer.luminous.protobuf.BluetoothServiceData> values) {
      if (manufacturerDataBuilder_ == null) {
        ensureManufacturerDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, manufacturerData_);
        onChanged();
      } else {
        manufacturerDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public Builder clearManufacturerData() {
      if (manufacturerDataBuilder_ == null) {
        manufacturerData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        manufacturerDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public Builder removeManufacturerData(int index) {
      if (manufacturerDataBuilder_ == null) {
        ensureManufacturerDataIsMutable();
        manufacturerData_.remove(index);
        onChanged();
      } else {
        manufacturerDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder getManufacturerDataBuilder(
        int index) {
      return getManufacturerDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder getManufacturerDataOrBuilder(
        int index) {
      if (manufacturerDataBuilder_ == null) {
        return manufacturerData_.get(index);  } else {
        return manufacturerDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public java.util.List<? extends it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder> 
         getManufacturerDataOrBuilderList() {
      if (manufacturerDataBuilder_ != null) {
        return manufacturerDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(manufacturerData_);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder addManufacturerDataBuilder() {
      return getManufacturerDataFieldBuilder().addBuilder(
          it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.getDefaultInstance());
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder addManufacturerDataBuilder(
        int index) {
      return getManufacturerDataFieldBuilder().addBuilder(
          index, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.getDefaultInstance());
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.BluetoothServiceData manufacturer_data = 6;</code>
     */
    public java.util.List<it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder> 
         getManufacturerDataBuilderList() {
      return getManufacturerDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        it.achdjian.saucer.luminous.protobuf.BluetoothServiceData, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder, it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder> 
        getManufacturerDataFieldBuilder() {
      if (manufacturerDataBuilder_ == null) {
        manufacturerDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            it.achdjian.saucer.luminous.protobuf.BluetoothServiceData, it.achdjian.saucer.luminous.protobuf.BluetoothServiceData.Builder, it.achdjian.saucer.luminous.protobuf.BluetoothServiceDataOrBuilder>(
                manufacturerData_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        manufacturerData_ = null;
      }
      return manufacturerDataBuilder_;
    }

    private int addressType_ ;
    /**
     * <code>uint32 address_type = 7;</code>
     * @return The addressType.
     */
    @java.lang.Override
    public int getAddressType() {
      return addressType_;
    }
    /**
     * <code>uint32 address_type = 7;</code>
     * @param value The addressType to set.
     * @return This builder for chaining.
     */
    public Builder setAddressType(int value) {
      
      addressType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 address_type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddressType() {
      bitField0_ = (bitField0_ & ~0x00000040);
      addressType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothLEAdvertisementResponse)
  }

  // @@protoc_insertion_point(class_scope:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothLEAdvertisementResponse)
  private static final it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse();
  }

  public static it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BluetoothLEAdvertisementResponse>
      PARSER = new com.google.protobuf.AbstractParser<BluetoothLEAdvertisementResponse>() {
    @java.lang.Override
    public BluetoothLEAdvertisementResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BluetoothLEAdvertisementResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BluetoothLEAdvertisementResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.BluetoothLEAdvertisementResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

