// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.saucer.luminous.protobuf;

public interface BluetoothGATTGetServicesDoneResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.achdjian.sottovasoluminoso.protobuf.java.BluetoothGATTGetServicesDoneResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 address = 1;</code>
   * @return The address.
   */
  long getAddress();
}
