//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

package it.achdjian.saucer.luminous.protobuf;

@kotlin.jvm.JvmName("-initializedeviceInfoRequest")
public inline fun deviceInfoRequest(block: it.achdjian.saucer.luminous.protobuf.DeviceInfoRequestKt.Dsl.() -> kotlin.Unit): it.achdjian.saucer.luminous.protobuf.DeviceInfoRequest =
  it.achdjian.saucer.luminous.protobuf.DeviceInfoRequestKt.Dsl._create(it.achdjian.saucer.luminous.protobuf.DeviceInfoRequest.newBuilder()).apply { block() }._build()
public object DeviceInfoRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: it.achdjian.saucer.luminous.protobuf.DeviceInfoRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: it.achdjian.saucer.luminous.protobuf.DeviceInfoRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): it.achdjian.saucer.luminous.protobuf.DeviceInfoRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun it.achdjian.saucer.luminous.protobuf.DeviceInfoRequest.copy(block: it.achdjian.saucer.luminous.protobuf.DeviceInfoRequestKt.Dsl.() -> kotlin.Unit): it.achdjian.saucer.luminous.protobuf.DeviceInfoRequest =
  it.achdjian.saucer.luminous.protobuf.DeviceInfoRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

