// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.saucer.luminous.protobuf;

/**
 * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest}
 */
public final class FanCommandRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest)
    FanCommandRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FanCommandRequest.newBuilder() to construct.
  private FanCommandRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FanCommandRequest() {
    speed_ = 0;
    direction_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FanCommandRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_FanCommandRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_FanCommandRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            it.achdjian.saucer.luminous.protobuf.FanCommandRequest.class, it.achdjian.saucer.luminous.protobuf.FanCommandRequest.Builder.class);
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private int key_ = 0;
  /**
   * <code>fixed32 key = 1;</code>
   * @return The key.
   */
  @java.lang.Override
  public int getKey() {
    return key_;
  }

  public static final int HAS_STATE_FIELD_NUMBER = 2;
  private boolean hasState_ = false;
  /**
   * <code>bool has_state = 2;</code>
   * @return The hasState.
   */
  @java.lang.Override
  public boolean getHasState() {
    return hasState_;
  }

  public static final int STATE_FIELD_NUMBER = 3;
  private boolean state_ = false;
  /**
   * <code>bool state = 3;</code>
   * @return The state.
   */
  @java.lang.Override
  public boolean getState() {
    return state_;
  }

  public static final int HAS_SPEED_FIELD_NUMBER = 4;
  private boolean hasSpeed_ = false;
  /**
   * <code>bool has_speed = 4 [deprecated = true];</code>
   * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.has_speed is deprecated.
   *     See api.proto;l=389
   * @return The hasSpeed.
   */
  @java.lang.Override
  @java.lang.Deprecated public boolean getHasSpeed() {
    return hasSpeed_;
  }

  public static final int SPEED_FIELD_NUMBER = 5;
  private int speed_ = 0;
  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanSpeed speed = 5 [deprecated = true];</code>
   * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.speed is deprecated.
   *     See api.proto;l=390
   * @return The enum numeric value on the wire for speed.
   */
  @java.lang.Override @java.lang.Deprecated public int getSpeedValue() {
    return speed_;
  }
  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanSpeed speed = 5 [deprecated = true];</code>
   * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.speed is deprecated.
   *     See api.proto;l=390
   * @return The speed.
   */
  @java.lang.Override @java.lang.Deprecated public it.achdjian.saucer.luminous.protobuf.FanSpeed getSpeed() {
    it.achdjian.saucer.luminous.protobuf.FanSpeed result = it.achdjian.saucer.luminous.protobuf.FanSpeed.forNumber(speed_);
    return result == null ? it.achdjian.saucer.luminous.protobuf.FanSpeed.UNRECOGNIZED : result;
  }

  public static final int HAS_OSCILLATING_FIELD_NUMBER = 6;
  private boolean hasOscillating_ = false;
  /**
   * <code>bool has_oscillating = 6;</code>
   * @return The hasOscillating.
   */
  @java.lang.Override
  public boolean getHasOscillating() {
    return hasOscillating_;
  }

  public static final int OSCILLATING_FIELD_NUMBER = 7;
  private boolean oscillating_ = false;
  /**
   * <code>bool oscillating = 7;</code>
   * @return The oscillating.
   */
  @java.lang.Override
  public boolean getOscillating() {
    return oscillating_;
  }

  public static final int HAS_DIRECTION_FIELD_NUMBER = 8;
  private boolean hasDirection_ = false;
  /**
   * <code>bool has_direction = 8;</code>
   * @return The hasDirection.
   */
  @java.lang.Override
  public boolean getHasDirection() {
    return hasDirection_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 9;
  private int direction_ = 0;
  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanDirection direction = 9;</code>
   * @return The enum numeric value on the wire for direction.
   */
  @java.lang.Override public int getDirectionValue() {
    return direction_;
  }
  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanDirection direction = 9;</code>
   * @return The direction.
   */
  @java.lang.Override public it.achdjian.saucer.luminous.protobuf.FanDirection getDirection() {
    it.achdjian.saucer.luminous.protobuf.FanDirection result = it.achdjian.saucer.luminous.protobuf.FanDirection.forNumber(direction_);
    return result == null ? it.achdjian.saucer.luminous.protobuf.FanDirection.UNRECOGNIZED : result;
  }

  public static final int HAS_SPEED_LEVEL_FIELD_NUMBER = 10;
  private boolean hasSpeedLevel_ = false;
  /**
   * <code>bool has_speed_level = 10;</code>
   * @return The hasSpeedLevel.
   */
  @java.lang.Override
  public boolean getHasSpeedLevel() {
    return hasSpeedLevel_;
  }

  public static final int SPEED_LEVEL_FIELD_NUMBER = 11;
  private int speedLevel_ = 0;
  /**
   * <code>int32 speed_level = 11;</code>
   * @return The speedLevel.
   */
  @java.lang.Override
  public int getSpeedLevel() {
    return speedLevel_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (key_ != 0) {
      output.writeFixed32(1, key_);
    }
    if (hasState_ != false) {
      output.writeBool(2, hasState_);
    }
    if (state_ != false) {
      output.writeBool(3, state_);
    }
    if (hasSpeed_ != false) {
      output.writeBool(4, hasSpeed_);
    }
    if (speed_ != it.achdjian.saucer.luminous.protobuf.FanSpeed.FAN_SPEED_LOW.getNumber()) {
      output.writeEnum(5, speed_);
    }
    if (hasOscillating_ != false) {
      output.writeBool(6, hasOscillating_);
    }
    if (oscillating_ != false) {
      output.writeBool(7, oscillating_);
    }
    if (hasDirection_ != false) {
      output.writeBool(8, hasDirection_);
    }
    if (direction_ != it.achdjian.saucer.luminous.protobuf.FanDirection.FAN_DIRECTION_FORWARD.getNumber()) {
      output.writeEnum(9, direction_);
    }
    if (hasSpeedLevel_ != false) {
      output.writeBool(10, hasSpeedLevel_);
    }
    if (speedLevel_ != 0) {
      output.writeInt32(11, speedLevel_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (key_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(1, key_);
    }
    if (hasState_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, hasState_);
    }
    if (state_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, state_);
    }
    if (hasSpeed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, hasSpeed_);
    }
    if (speed_ != it.achdjian.saucer.luminous.protobuf.FanSpeed.FAN_SPEED_LOW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, speed_);
    }
    if (hasOscillating_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, hasOscillating_);
    }
    if (oscillating_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, oscillating_);
    }
    if (hasDirection_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, hasDirection_);
    }
    if (direction_ != it.achdjian.saucer.luminous.protobuf.FanDirection.FAN_DIRECTION_FORWARD.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, direction_);
    }
    if (hasSpeedLevel_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, hasSpeedLevel_);
    }
    if (speedLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, speedLevel_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof it.achdjian.saucer.luminous.protobuf.FanCommandRequest)) {
      return super.equals(obj);
    }
    it.achdjian.saucer.luminous.protobuf.FanCommandRequest other = (it.achdjian.saucer.luminous.protobuf.FanCommandRequest) obj;

    if (getKey()
        != other.getKey()) return false;
    if (getHasState()
        != other.getHasState()) return false;
    if (getState()
        != other.getState()) return false;
    if (getHasSpeed()
        != other.getHasSpeed()) return false;
    if (speed_ != other.speed_) return false;
    if (getHasOscillating()
        != other.getHasOscillating()) return false;
    if (getOscillating()
        != other.getOscillating()) return false;
    if (getHasDirection()
        != other.getHasDirection()) return false;
    if (direction_ != other.direction_) return false;
    if (getHasSpeedLevel()
        != other.getHasSpeedLevel()) return false;
    if (getSpeedLevel()
        != other.getSpeedLevel()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey();
    hash = (37 * hash) + HAS_STATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasState());
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getState());
    hash = (37 * hash) + HAS_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasSpeed());
    hash = (37 * hash) + SPEED_FIELD_NUMBER;
    hash = (53 * hash) + speed_;
    hash = (37 * hash) + HAS_OSCILLATING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasOscillating());
    hash = (37 * hash) + OSCILLATING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOscillating());
    hash = (37 * hash) + HAS_DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasDirection());
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + direction_;
    hash = (37 * hash) + HAS_SPEED_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasSpeedLevel());
    hash = (37 * hash) + SPEED_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getSpeedLevel();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(it.achdjian.saucer.luminous.protobuf.FanCommandRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest)
      it.achdjian.saucer.luminous.protobuf.FanCommandRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_FanCommandRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_FanCommandRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.achdjian.saucer.luminous.protobuf.FanCommandRequest.class, it.achdjian.saucer.luminous.protobuf.FanCommandRequest.Builder.class);
    }

    // Construct using it.achdjian.saucer.luminous.protobuf.FanCommandRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      key_ = 0;
      hasState_ = false;
      state_ = false;
      hasSpeed_ = false;
      speed_ = 0;
      hasOscillating_ = false;
      oscillating_ = false;
      hasDirection_ = false;
      direction_ = 0;
      hasSpeedLevel_ = false;
      speedLevel_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_FanCommandRequest_descriptor;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.FanCommandRequest getDefaultInstanceForType() {
      return it.achdjian.saucer.luminous.protobuf.FanCommandRequest.getDefaultInstance();
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.FanCommandRequest build() {
      it.achdjian.saucer.luminous.protobuf.FanCommandRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.FanCommandRequest buildPartial() {
      it.achdjian.saucer.luminous.protobuf.FanCommandRequest result = new it.achdjian.saucer.luminous.protobuf.FanCommandRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(it.achdjian.saucer.luminous.protobuf.FanCommandRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.key_ = key_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hasState_ = hasState_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.state_ = state_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.hasSpeed_ = hasSpeed_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.speed_ = speed_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.hasOscillating_ = hasOscillating_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.oscillating_ = oscillating_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.hasDirection_ = hasDirection_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.direction_ = direction_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.hasSpeedLevel_ = hasSpeedLevel_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.speedLevel_ = speedLevel_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof it.achdjian.saucer.luminous.protobuf.FanCommandRequest) {
        return mergeFrom((it.achdjian.saucer.luminous.protobuf.FanCommandRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(it.achdjian.saucer.luminous.protobuf.FanCommandRequest other) {
      if (other == it.achdjian.saucer.luminous.protobuf.FanCommandRequest.getDefaultInstance()) return this;
      if (other.getKey() != 0) {
        setKey(other.getKey());
      }
      if (other.getHasState() != false) {
        setHasState(other.getHasState());
      }
      if (other.getState() != false) {
        setState(other.getState());
      }
      if (other.getHasSpeed() != false) {
        setHasSpeed(other.getHasSpeed());
      }
      if (other.speed_ != 0) {
        setSpeedValue(other.getSpeedValue());
      }
      if (other.getHasOscillating() != false) {
        setHasOscillating(other.getHasOscillating());
      }
      if (other.getOscillating() != false) {
        setOscillating(other.getOscillating());
      }
      if (other.getHasDirection() != false) {
        setHasDirection(other.getHasDirection());
      }
      if (other.direction_ != 0) {
        setDirectionValue(other.getDirectionValue());
      }
      if (other.getHasSpeedLevel() != false) {
        setHasSpeedLevel(other.getHasSpeedLevel());
      }
      if (other.getSpeedLevel() != 0) {
        setSpeedLevel(other.getSpeedLevel());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              key_ = input.readFixed32();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 16: {
              hasState_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              state_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              hasSpeed_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              speed_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              hasOscillating_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              oscillating_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              hasDirection_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              direction_ = input.readEnum();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              hasSpeedLevel_ = input.readBool();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              speedLevel_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int key_ ;
    /**
     * <code>fixed32 key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public int getKey() {
      return key_;
    }
    /**
     * <code>fixed32 key = 1;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(int value) {
      
      key_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>fixed32 key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      bitField0_ = (bitField0_ & ~0x00000001);
      key_ = 0;
      onChanged();
      return this;
    }

    private boolean hasState_ ;
    /**
     * <code>bool has_state = 2;</code>
     * @return The hasState.
     */
    @java.lang.Override
    public boolean getHasState() {
      return hasState_;
    }
    /**
     * <code>bool has_state = 2;</code>
     * @param value The hasState to set.
     * @return This builder for chaining.
     */
    public Builder setHasState(boolean value) {
      
      hasState_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasState() {
      bitField0_ = (bitField0_ & ~0x00000002);
      hasState_ = false;
      onChanged();
      return this;
    }

    private boolean state_ ;
    /**
     * <code>bool state = 3;</code>
     * @return The state.
     */
    @java.lang.Override
    public boolean getState() {
      return state_;
    }
    /**
     * <code>bool state = 3;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(boolean value) {
      
      state_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool state = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000004);
      state_ = false;
      onChanged();
      return this;
    }

    private boolean hasSpeed_ ;
    /**
     * <code>bool has_speed = 4 [deprecated = true];</code>
     * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.has_speed is deprecated.
     *     See api.proto;l=389
     * @return The hasSpeed.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean getHasSpeed() {
      return hasSpeed_;
    }
    /**
     * <code>bool has_speed = 4 [deprecated = true];</code>
     * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.has_speed is deprecated.
     *     See api.proto;l=389
     * @param value The hasSpeed to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setHasSpeed(boolean value) {
      
      hasSpeed_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_speed = 4 [deprecated = true];</code>
     * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.has_speed is deprecated.
     *     See api.proto;l=389
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearHasSpeed() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hasSpeed_ = false;
      onChanged();
      return this;
    }

    private int speed_ = 0;
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanSpeed speed = 5 [deprecated = true];</code>
     * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.speed is deprecated.
     *     See api.proto;l=390
     * @return The enum numeric value on the wire for speed.
     */
    @java.lang.Override @java.lang.Deprecated public int getSpeedValue() {
      return speed_;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanSpeed speed = 5 [deprecated = true];</code>
     * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.speed is deprecated.
     *     See api.proto;l=390
     * @param value The enum numeric value on the wire for speed to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setSpeedValue(int value) {
      speed_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanSpeed speed = 5 [deprecated = true];</code>
     * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.speed is deprecated.
     *     See api.proto;l=390
     * @return The speed.
     */
    @java.lang.Override
    @java.lang.Deprecated public it.achdjian.saucer.luminous.protobuf.FanSpeed getSpeed() {
      it.achdjian.saucer.luminous.protobuf.FanSpeed result = it.achdjian.saucer.luminous.protobuf.FanSpeed.forNumber(speed_);
      return result == null ? it.achdjian.saucer.luminous.protobuf.FanSpeed.UNRECOGNIZED : result;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanSpeed speed = 5 [deprecated = true];</code>
     * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.speed is deprecated.
     *     See api.proto;l=390
     * @param value The speed to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setSpeed(it.achdjian.saucer.luminous.protobuf.FanSpeed value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      speed_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanSpeed speed = 5 [deprecated = true];</code>
     * @deprecated it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest.speed is deprecated.
     *     See api.proto;l=390
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearSpeed() {
      bitField0_ = (bitField0_ & ~0x00000010);
      speed_ = 0;
      onChanged();
      return this;
    }

    private boolean hasOscillating_ ;
    /**
     * <code>bool has_oscillating = 6;</code>
     * @return The hasOscillating.
     */
    @java.lang.Override
    public boolean getHasOscillating() {
      return hasOscillating_;
    }
    /**
     * <code>bool has_oscillating = 6;</code>
     * @param value The hasOscillating to set.
     * @return This builder for chaining.
     */
    public Builder setHasOscillating(boolean value) {
      
      hasOscillating_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_oscillating = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasOscillating() {
      bitField0_ = (bitField0_ & ~0x00000020);
      hasOscillating_ = false;
      onChanged();
      return this;
    }

    private boolean oscillating_ ;
    /**
     * <code>bool oscillating = 7;</code>
     * @return The oscillating.
     */
    @java.lang.Override
    public boolean getOscillating() {
      return oscillating_;
    }
    /**
     * <code>bool oscillating = 7;</code>
     * @param value The oscillating to set.
     * @return This builder for chaining.
     */
    public Builder setOscillating(boolean value) {
      
      oscillating_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool oscillating = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOscillating() {
      bitField0_ = (bitField0_ & ~0x00000040);
      oscillating_ = false;
      onChanged();
      return this;
    }

    private boolean hasDirection_ ;
    /**
     * <code>bool has_direction = 8;</code>
     * @return The hasDirection.
     */
    @java.lang.Override
    public boolean getHasDirection() {
      return hasDirection_;
    }
    /**
     * <code>bool has_direction = 8;</code>
     * @param value The hasDirection to set.
     * @return This builder for chaining.
     */
    public Builder setHasDirection(boolean value) {
      
      hasDirection_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_direction = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasDirection() {
      bitField0_ = (bitField0_ & ~0x00000080);
      hasDirection_ = false;
      onChanged();
      return this;
    }

    private int direction_ = 0;
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanDirection direction = 9;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override public int getDirectionValue() {
      return direction_;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanDirection direction = 9;</code>
     * @param value The enum numeric value on the wire for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionValue(int value) {
      direction_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanDirection direction = 9;</code>
     * @return The direction.
     */
    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.FanDirection getDirection() {
      it.achdjian.saucer.luminous.protobuf.FanDirection result = it.achdjian.saucer.luminous.protobuf.FanDirection.forNumber(direction_);
      return result == null ? it.achdjian.saucer.luminous.protobuf.FanDirection.UNRECOGNIZED : result;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanDirection direction = 9;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(it.achdjian.saucer.luminous.protobuf.FanDirection value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000100;
      direction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.it.achdjian.sottovasoluminoso.protobuf.java.FanDirection direction = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      bitField0_ = (bitField0_ & ~0x00000100);
      direction_ = 0;
      onChanged();
      return this;
    }

    private boolean hasSpeedLevel_ ;
    /**
     * <code>bool has_speed_level = 10;</code>
     * @return The hasSpeedLevel.
     */
    @java.lang.Override
    public boolean getHasSpeedLevel() {
      return hasSpeedLevel_;
    }
    /**
     * <code>bool has_speed_level = 10;</code>
     * @param value The hasSpeedLevel to set.
     * @return This builder for chaining.
     */
    public Builder setHasSpeedLevel(boolean value) {
      
      hasSpeedLevel_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_speed_level = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasSpeedLevel() {
      bitField0_ = (bitField0_ & ~0x00000200);
      hasSpeedLevel_ = false;
      onChanged();
      return this;
    }

    private int speedLevel_ ;
    /**
     * <code>int32 speed_level = 11;</code>
     * @return The speedLevel.
     */
    @java.lang.Override
    public int getSpeedLevel() {
      return speedLevel_;
    }
    /**
     * <code>int32 speed_level = 11;</code>
     * @param value The speedLevel to set.
     * @return This builder for chaining.
     */
    public Builder setSpeedLevel(int value) {
      
      speedLevel_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 speed_level = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeedLevel() {
      bitField0_ = (bitField0_ & ~0x00000400);
      speedLevel_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest)
  }

  // @@protoc_insertion_point(class_scope:it.achdjian.sottovasoluminoso.protobuf.java.FanCommandRequest)
  private static final it.achdjian.saucer.luminous.protobuf.FanCommandRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new it.achdjian.saucer.luminous.protobuf.FanCommandRequest();
  }

  public static it.achdjian.saucer.luminous.protobuf.FanCommandRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FanCommandRequest>
      PARSER = new com.google.protobuf.AbstractParser<FanCommandRequest>() {
    @java.lang.Override
    public FanCommandRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FanCommandRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FanCommandRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.FanCommandRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

