//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

package it.achdjian.saucer.luminous.protobuf;

@kotlin.jvm.JvmName("-initializegetTimeRequest")
public inline fun getTimeRequest(block: it.achdjian.saucer.luminous.protobuf.GetTimeRequestKt.Dsl.() -> kotlin.Unit): it.achdjian.saucer.luminous.protobuf.GetTimeRequest =
  it.achdjian.saucer.luminous.protobuf.GetTimeRequestKt.Dsl._create(it.achdjian.saucer.luminous.protobuf.GetTimeRequest.newBuilder()).apply { block() }._build()
public object GetTimeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: it.achdjian.saucer.luminous.protobuf.GetTimeRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: it.achdjian.saucer.luminous.protobuf.GetTimeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): it.achdjian.saucer.luminous.protobuf.GetTimeRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun it.achdjian.saucer.luminous.protobuf.GetTimeRequest.copy(block: it.achdjian.saucer.luminous.protobuf.GetTimeRequestKt.Dsl.() -> kotlin.Unit): it.achdjian.saucer.luminous.protobuf.GetTimeRequest =
  it.achdjian.saucer.luminous.protobuf.GetTimeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

