// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.saucer.luminous.protobuf;

/**
 * <pre>
 * Message sent at the beginning of each connection
 * Can only be sent by the client and only at the beginning of the connection
 * </pre>
 *
 * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.HelloRequest}
 */
public final class HelloRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:it.achdjian.sottovasoluminoso.protobuf.java.HelloRequest)
    HelloRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HelloRequest.newBuilder() to construct.
  private HelloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HelloRequest() {
    clientInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HelloRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_HelloRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_HelloRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            it.achdjian.saucer.luminous.protobuf.HelloRequest.class, it.achdjian.saucer.luminous.protobuf.HelloRequest.Builder.class);
  }

  public static final int CLIENT_INFO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientInfo_ = "";
  /**
   * <pre>
   * Description of client (like User Agent)
   * For example "Home Assistant"
   * Not strictly necessary to send but nice for debugging
   * purposes.
   * </pre>
   *
   * <code>string client_info = 1;</code>
   * @return The clientInfo.
   */
  @java.lang.Override
  public java.lang.String getClientInfo() {
    java.lang.Object ref = clientInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientInfo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Description of client (like User Agent)
   * For example "Home Assistant"
   * Not strictly necessary to send but nice for debugging
   * purposes.
   * </pre>
   *
   * <code>string client_info = 1;</code>
   * @return The bytes for clientInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientInfoBytes() {
    java.lang.Object ref = clientInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int API_VERSION_MAJOR_FIELD_NUMBER = 2;
  private int apiVersionMajor_ = 0;
  /**
   * <code>uint32 api_version_major = 2;</code>
   * @return The apiVersionMajor.
   */
  @java.lang.Override
  public int getApiVersionMajor() {
    return apiVersionMajor_;
  }

  public static final int API_VERSION_MINOR_FIELD_NUMBER = 3;
  private int apiVersionMinor_ = 0;
  /**
   * <code>uint32 api_version_minor = 3;</code>
   * @return The apiVersionMinor.
   */
  @java.lang.Override
  public int getApiVersionMinor() {
    return apiVersionMinor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientInfo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientInfo_);
    }
    if (apiVersionMajor_ != 0) {
      output.writeUInt32(2, apiVersionMajor_);
    }
    if (apiVersionMinor_ != 0) {
      output.writeUInt32(3, apiVersionMinor_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientInfo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientInfo_);
    }
    if (apiVersionMajor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, apiVersionMajor_);
    }
    if (apiVersionMinor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, apiVersionMinor_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof it.achdjian.saucer.luminous.protobuf.HelloRequest)) {
      return super.equals(obj);
    }
    it.achdjian.saucer.luminous.protobuf.HelloRequest other = (it.achdjian.saucer.luminous.protobuf.HelloRequest) obj;

    if (!getClientInfo()
        .equals(other.getClientInfo())) return false;
    if (getApiVersionMajor()
        != other.getApiVersionMajor()) return false;
    if (getApiVersionMinor()
        != other.getApiVersionMinor()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENT_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getClientInfo().hashCode();
    hash = (37 * hash) + API_VERSION_MAJOR_FIELD_NUMBER;
    hash = (53 * hash) + getApiVersionMajor();
    hash = (37 * hash) + API_VERSION_MINOR_FIELD_NUMBER;
    hash = (53 * hash) + getApiVersionMinor();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.HelloRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(it.achdjian.saucer.luminous.protobuf.HelloRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message sent at the beginning of each connection
   * Can only be sent by the client and only at the beginning of the connection
   * </pre>
   *
   * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.HelloRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:it.achdjian.sottovasoluminoso.protobuf.java.HelloRequest)
      it.achdjian.saucer.luminous.protobuf.HelloRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_HelloRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_HelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.achdjian.saucer.luminous.protobuf.HelloRequest.class, it.achdjian.saucer.luminous.protobuf.HelloRequest.Builder.class);
    }

    // Construct using it.achdjian.saucer.luminous.protobuf.HelloRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      clientInfo_ = "";
      apiVersionMajor_ = 0;
      apiVersionMinor_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_HelloRequest_descriptor;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.HelloRequest getDefaultInstanceForType() {
      return it.achdjian.saucer.luminous.protobuf.HelloRequest.getDefaultInstance();
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.HelloRequest build() {
      it.achdjian.saucer.luminous.protobuf.HelloRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.HelloRequest buildPartial() {
      it.achdjian.saucer.luminous.protobuf.HelloRequest result = new it.achdjian.saucer.luminous.protobuf.HelloRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(it.achdjian.saucer.luminous.protobuf.HelloRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.clientInfo_ = clientInfo_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.apiVersionMajor_ = apiVersionMajor_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.apiVersionMinor_ = apiVersionMinor_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof it.achdjian.saucer.luminous.protobuf.HelloRequest) {
        return mergeFrom((it.achdjian.saucer.luminous.protobuf.HelloRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(it.achdjian.saucer.luminous.protobuf.HelloRequest other) {
      if (other == it.achdjian.saucer.luminous.protobuf.HelloRequest.getDefaultInstance()) return this;
      if (!other.getClientInfo().isEmpty()) {
        clientInfo_ = other.clientInfo_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getApiVersionMajor() != 0) {
        setApiVersionMajor(other.getApiVersionMajor());
      }
      if (other.getApiVersionMinor() != 0) {
        setApiVersionMinor(other.getApiVersionMinor());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              clientInfo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              apiVersionMajor_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              apiVersionMinor_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object clientInfo_ = "";
    /**
     * <pre>
     * Description of client (like User Agent)
     * For example "Home Assistant"
     * Not strictly necessary to send but nice for debugging
     * purposes.
     * </pre>
     *
     * <code>string client_info = 1;</code>
     * @return The clientInfo.
     */
    public java.lang.String getClientInfo() {
      java.lang.Object ref = clientInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Description of client (like User Agent)
     * For example "Home Assistant"
     * Not strictly necessary to send but nice for debugging
     * purposes.
     * </pre>
     *
     * <code>string client_info = 1;</code>
     * @return The bytes for clientInfo.
     */
    public com.google.protobuf.ByteString
        getClientInfoBytes() {
      java.lang.Object ref = clientInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Description of client (like User Agent)
     * For example "Home Assistant"
     * Not strictly necessary to send but nice for debugging
     * purposes.
     * </pre>
     *
     * <code>string client_info = 1;</code>
     * @param value The clientInfo to set.
     * @return This builder for chaining.
     */
    public Builder setClientInfo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientInfo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Description of client (like User Agent)
     * For example "Home Assistant"
     * Not strictly necessary to send but nice for debugging
     * purposes.
     * </pre>
     *
     * <code>string client_info = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientInfo() {
      clientInfo_ = getDefaultInstance().getClientInfo();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Description of client (like User Agent)
     * For example "Home Assistant"
     * Not strictly necessary to send but nice for debugging
     * purposes.
     * </pre>
     *
     * <code>string client_info = 1;</code>
     * @param value The bytes for clientInfo to set.
     * @return This builder for chaining.
     */
    public Builder setClientInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientInfo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int apiVersionMajor_ ;
    /**
     * <code>uint32 api_version_major = 2;</code>
     * @return The apiVersionMajor.
     */
    @java.lang.Override
    public int getApiVersionMajor() {
      return apiVersionMajor_;
    }
    /**
     * <code>uint32 api_version_major = 2;</code>
     * @param value The apiVersionMajor to set.
     * @return This builder for chaining.
     */
    public Builder setApiVersionMajor(int value) {
      
      apiVersionMajor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 api_version_major = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearApiVersionMajor() {
      bitField0_ = (bitField0_ & ~0x00000002);
      apiVersionMajor_ = 0;
      onChanged();
      return this;
    }

    private int apiVersionMinor_ ;
    /**
     * <code>uint32 api_version_minor = 3;</code>
     * @return The apiVersionMinor.
     */
    @java.lang.Override
    public int getApiVersionMinor() {
      return apiVersionMinor_;
    }
    /**
     * <code>uint32 api_version_minor = 3;</code>
     * @param value The apiVersionMinor to set.
     * @return This builder for chaining.
     */
    public Builder setApiVersionMinor(int value) {
      
      apiVersionMinor_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 api_version_minor = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearApiVersionMinor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      apiVersionMinor_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:it.achdjian.sottovasoluminoso.protobuf.java.HelloRequest)
  }

  // @@protoc_insertion_point(class_scope:it.achdjian.sottovasoluminoso.protobuf.java.HelloRequest)
  private static final it.achdjian.saucer.luminous.protobuf.HelloRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new it.achdjian.saucer.luminous.protobuf.HelloRequest();
  }

  public static it.achdjian.saucer.luminous.protobuf.HelloRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HelloRequest>
      PARSER = new com.google.protobuf.AbstractParser<HelloRequest>() {
    @java.lang.Override
    public HelloRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HelloRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HelloRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.HelloRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

