// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.saucer.luminous.protobuf;

/**
 * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceResponse}
 */
public final class HomeassistantServiceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceResponse)
    HomeassistantServiceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HomeassistantServiceResponse.newBuilder() to construct.
  private HomeassistantServiceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HomeassistantServiceResponse() {
    service_ = "";
    data_ = java.util.Collections.emptyList();
    dataTemplate_ = java.util.Collections.emptyList();
    variables_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HomeassistantServiceResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_HomeassistantServiceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_HomeassistantServiceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse.class, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse.Builder.class);
  }

  public static final int SERVICE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object service_ = "";
  /**
   * <code>string service = 1;</code>
   * @return The service.
   */
  @java.lang.Override
  public java.lang.String getService() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      service_ = s;
      return s;
    }
  }
  /**
   * <code>string service = 1;</code>
   * @return The bytes for service.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceBytes() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      service_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> data_;
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
   */
  @java.lang.Override
  public java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> getDataList() {
    return data_;
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> 
      getDataOrBuilderList() {
    return data_;
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
   */
  @java.lang.Override
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
   */
  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap getData(int index) {
    return data_.get(index);
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
   */
  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder getDataOrBuilder(
      int index) {
    return data_.get(index);
  }

  public static final int DATA_TEMPLATE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> dataTemplate_;
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
   */
  @java.lang.Override
  public java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> getDataTemplateList() {
    return dataTemplate_;
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> 
      getDataTemplateOrBuilderList() {
    return dataTemplate_;
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
   */
  @java.lang.Override
  public int getDataTemplateCount() {
    return dataTemplate_.size();
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
   */
  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap getDataTemplate(int index) {
    return dataTemplate_.get(index);
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
   */
  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder getDataTemplateOrBuilder(
      int index) {
    return dataTemplate_.get(index);
  }

  public static final int VARIABLES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> variables_;
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
   */
  @java.lang.Override
  public java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> getVariablesList() {
    return variables_;
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> 
      getVariablesOrBuilderList() {
    return variables_;
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
   */
  @java.lang.Override
  public int getVariablesCount() {
    return variables_.size();
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
   */
  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap getVariables(int index) {
    return variables_.get(index);
  }
  /**
   * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
   */
  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder getVariablesOrBuilder(
      int index) {
    return variables_.get(index);
  }

  public static final int IS_EVENT_FIELD_NUMBER = 5;
  private boolean isEvent_ = false;
  /**
   * <code>bool is_event = 5;</code>
   * @return The isEvent.
   */
  @java.lang.Override
  public boolean getIsEvent() {
    return isEvent_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(service_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, service_);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeMessage(2, data_.get(i));
    }
    for (int i = 0; i < dataTemplate_.size(); i++) {
      output.writeMessage(3, dataTemplate_.get(i));
    }
    for (int i = 0; i < variables_.size(); i++) {
      output.writeMessage(4, variables_.get(i));
    }
    if (isEvent_ != false) {
      output.writeBool(5, isEvent_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(service_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, service_);
    }
    for (int i = 0; i < data_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, data_.get(i));
    }
    for (int i = 0; i < dataTemplate_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, dataTemplate_.get(i));
    }
    for (int i = 0; i < variables_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, variables_.get(i));
    }
    if (isEvent_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isEvent_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse)) {
      return super.equals(obj);
    }
    it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse other = (it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse) obj;

    if (!getService()
        .equals(other.getService())) return false;
    if (!getDataList()
        .equals(other.getDataList())) return false;
    if (!getDataTemplateList()
        .equals(other.getDataTemplateList())) return false;
    if (!getVariablesList()
        .equals(other.getVariablesList())) return false;
    if (getIsEvent()
        != other.getIsEvent()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_FIELD_NUMBER;
    hash = (53 * hash) + getService().hashCode();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    if (getDataTemplateCount() > 0) {
      hash = (37 * hash) + DATA_TEMPLATE_FIELD_NUMBER;
      hash = (53 * hash) + getDataTemplateList().hashCode();
    }
    if (getVariablesCount() > 0) {
      hash = (37 * hash) + VARIABLES_FIELD_NUMBER;
      hash = (53 * hash) + getVariablesList().hashCode();
    }
    hash = (37 * hash) + IS_EVENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsEvent());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceResponse)
      it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_HomeassistantServiceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_HomeassistantServiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse.class, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse.Builder.class);
    }

    // Construct using it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      service_ = "";
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
      } else {
        data_ = null;
        dataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (dataTemplateBuilder_ == null) {
        dataTemplate_ = java.util.Collections.emptyList();
      } else {
        dataTemplate_ = null;
        dataTemplateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (variablesBuilder_ == null) {
        variables_ = java.util.Collections.emptyList();
      } else {
        variables_ = null;
        variablesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      isEvent_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return it.achdjian.saucer.luminous.protobuf.Api.internal_static_it_achdjian_sottovasoluminoso_protobuf_java_HomeassistantServiceResponse_descriptor;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse getDefaultInstanceForType() {
      return it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse build() {
      it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse buildPartial() {
      it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse result = new it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse result) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      if (dataTemplateBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          dataTemplate_ = java.util.Collections.unmodifiableList(dataTemplate_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.dataTemplate_ = dataTemplate_;
      } else {
        result.dataTemplate_ = dataTemplateBuilder_.build();
      }
      if (variablesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          variables_ = java.util.Collections.unmodifiableList(variables_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.variables_ = variables_;
      } else {
        result.variables_ = variablesBuilder_.build();
      }
    }

    private void buildPartial0(it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.service_ = service_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isEvent_ = isEvent_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse) {
        return mergeFrom((it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse other) {
      if (other == it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse.getDefaultInstance()) return this;
      if (!other.getService().isEmpty()) {
        service_ = other.service_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (dataBuilder_ == null) {
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
      } else {
        if (!other.data_.isEmpty()) {
          if (dataBuilder_.isEmpty()) {
            dataBuilder_.dispose();
            dataBuilder_ = null;
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
            dataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataFieldBuilder() : null;
          } else {
            dataBuilder_.addAllMessages(other.data_);
          }
        }
      }
      if (dataTemplateBuilder_ == null) {
        if (!other.dataTemplate_.isEmpty()) {
          if (dataTemplate_.isEmpty()) {
            dataTemplate_ = other.dataTemplate_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDataTemplateIsMutable();
            dataTemplate_.addAll(other.dataTemplate_);
          }
          onChanged();
        }
      } else {
        if (!other.dataTemplate_.isEmpty()) {
          if (dataTemplateBuilder_.isEmpty()) {
            dataTemplateBuilder_.dispose();
            dataTemplateBuilder_ = null;
            dataTemplate_ = other.dataTemplate_;
            bitField0_ = (bitField0_ & ~0x00000004);
            dataTemplateBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataTemplateFieldBuilder() : null;
          } else {
            dataTemplateBuilder_.addAllMessages(other.dataTemplate_);
          }
        }
      }
      if (variablesBuilder_ == null) {
        if (!other.variables_.isEmpty()) {
          if (variables_.isEmpty()) {
            variables_ = other.variables_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureVariablesIsMutable();
            variables_.addAll(other.variables_);
          }
          onChanged();
        }
      } else {
        if (!other.variables_.isEmpty()) {
          if (variablesBuilder_.isEmpty()) {
            variablesBuilder_.dispose();
            variablesBuilder_ = null;
            variables_ = other.variables_;
            bitField0_ = (bitField0_ & ~0x00000008);
            variablesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVariablesFieldBuilder() : null;
          } else {
            variablesBuilder_.addAllMessages(other.variables_);
          }
        }
      }
      if (other.getIsEvent() != false) {
        setIsEvent(other.getIsEvent());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              service_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap m =
                  input.readMessage(
                      it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.parser(),
                      extensionRegistry);
              if (dataBuilder_ == null) {
                ensureDataIsMutable();
                data_.add(m);
              } else {
                dataBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap m =
                  input.readMessage(
                      it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.parser(),
                      extensionRegistry);
              if (dataTemplateBuilder_ == null) {
                ensureDataTemplateIsMutable();
                dataTemplate_.add(m);
              } else {
                dataTemplateBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap m =
                  input.readMessage(
                      it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.parser(),
                      extensionRegistry);
              if (variablesBuilder_ == null) {
                ensureVariablesIsMutable();
                variables_.add(m);
              } else {
                variablesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 40: {
              isEvent_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object service_ = "";
    /**
     * <code>string service = 1;</code>
     * @return The service.
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        service_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service = 1;</code>
     * @return The bytes for service.
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service = 1;</code>
     * @param value The service to set.
     * @return This builder for chaining.
     */
    public Builder setService(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      service_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string service = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearService() {
      service_ = getDefaultInstance().getService();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string service = 1;</code>
     * @param value The bytes for service to set.
     * @return This builder for chaining.
     */
    public Builder setServiceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      service_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> data_ =
      java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        data_ = new java.util.ArrayList<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap>(data_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> dataBuilder_;

    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> getDataList() {
      if (dataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(data_);
      } else {
        return dataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public int getDataCount() {
      if (dataBuilder_ == null) {
        return data_.size();
      } else {
        return dataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap getData(int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);
      } else {
        return dataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public Builder setData(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
      } else {
        dataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public Builder setData(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public Builder addData(it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
      } else {
        dataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public Builder addData(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataIsMutable();
        data_.add(index, value);
        onChanged();
      } else {
        dataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public Builder addData(
        it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public Builder addData(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder builderForValue) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> values) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
      } else {
        dataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public Builder removeData(int index) {
      if (dataBuilder_ == null) {
        ensureDataIsMutable();
        data_.remove(index);
        onChanged();
      } else {
        dataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder getDataBuilder(
        int index) {
      return getDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder getDataOrBuilder(
        int index) {
      if (dataBuilder_ == null) {
        return data_.get(index);  } else {
        return dataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public java.util.List<? extends it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> 
         getDataOrBuilderList() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(data_);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder addDataBuilder() {
      return getDataFieldBuilder().addBuilder(
          it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.getDefaultInstance());
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder addDataBuilder(
        int index) {
      return getDataFieldBuilder().addBuilder(
          index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.getDefaultInstance());
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data = 2;</code>
     */
    public java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder> 
         getDataBuilderList() {
      return getDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder>(
                data_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> dataTemplate_ =
      java.util.Collections.emptyList();
    private void ensureDataTemplateIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        dataTemplate_ = new java.util.ArrayList<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap>(dataTemplate_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> dataTemplateBuilder_;

    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> getDataTemplateList() {
      if (dataTemplateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dataTemplate_);
      } else {
        return dataTemplateBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public int getDataTemplateCount() {
      if (dataTemplateBuilder_ == null) {
        return dataTemplate_.size();
      } else {
        return dataTemplateBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap getDataTemplate(int index) {
      if (dataTemplateBuilder_ == null) {
        return dataTemplate_.get(index);
      } else {
        return dataTemplateBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public Builder setDataTemplate(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap value) {
      if (dataTemplateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataTemplateIsMutable();
        dataTemplate_.set(index, value);
        onChanged();
      } else {
        dataTemplateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public Builder setDataTemplate(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder builderForValue) {
      if (dataTemplateBuilder_ == null) {
        ensureDataTemplateIsMutable();
        dataTemplate_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataTemplateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public Builder addDataTemplate(it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap value) {
      if (dataTemplateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataTemplateIsMutable();
        dataTemplate_.add(value);
        onChanged();
      } else {
        dataTemplateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public Builder addDataTemplate(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap value) {
      if (dataTemplateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataTemplateIsMutable();
        dataTemplate_.add(index, value);
        onChanged();
      } else {
        dataTemplateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public Builder addDataTemplate(
        it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder builderForValue) {
      if (dataTemplateBuilder_ == null) {
        ensureDataTemplateIsMutable();
        dataTemplate_.add(builderForValue.build());
        onChanged();
      } else {
        dataTemplateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public Builder addDataTemplate(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder builderForValue) {
      if (dataTemplateBuilder_ == null) {
        ensureDataTemplateIsMutable();
        dataTemplate_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataTemplateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public Builder addAllDataTemplate(
        java.lang.Iterable<? extends it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> values) {
      if (dataTemplateBuilder_ == null) {
        ensureDataTemplateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dataTemplate_);
        onChanged();
      } else {
        dataTemplateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public Builder clearDataTemplate() {
      if (dataTemplateBuilder_ == null) {
        dataTemplate_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        dataTemplateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public Builder removeDataTemplate(int index) {
      if (dataTemplateBuilder_ == null) {
        ensureDataTemplateIsMutable();
        dataTemplate_.remove(index);
        onChanged();
      } else {
        dataTemplateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder getDataTemplateBuilder(
        int index) {
      return getDataTemplateFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder getDataTemplateOrBuilder(
        int index) {
      if (dataTemplateBuilder_ == null) {
        return dataTemplate_.get(index);  } else {
        return dataTemplateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public java.util.List<? extends it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> 
         getDataTemplateOrBuilderList() {
      if (dataTemplateBuilder_ != null) {
        return dataTemplateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dataTemplate_);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder addDataTemplateBuilder() {
      return getDataTemplateFieldBuilder().addBuilder(
          it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.getDefaultInstance());
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder addDataTemplateBuilder(
        int index) {
      return getDataTemplateFieldBuilder().addBuilder(
          index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.getDefaultInstance());
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap data_template = 3;</code>
     */
    public java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder> 
         getDataTemplateBuilderList() {
      return getDataTemplateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> 
        getDataTemplateFieldBuilder() {
      if (dataTemplateBuilder_ == null) {
        dataTemplateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder>(
                dataTemplate_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        dataTemplate_ = null;
      }
      return dataTemplateBuilder_;
    }

    private java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> variables_ =
      java.util.Collections.emptyList();
    private void ensureVariablesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        variables_ = new java.util.ArrayList<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap>(variables_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> variablesBuilder_;

    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> getVariablesList() {
      if (variablesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(variables_);
      } else {
        return variablesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public int getVariablesCount() {
      if (variablesBuilder_ == null) {
        return variables_.size();
      } else {
        return variablesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap getVariables(int index) {
      if (variablesBuilder_ == null) {
        return variables_.get(index);
      } else {
        return variablesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public Builder setVariables(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap value) {
      if (variablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariablesIsMutable();
        variables_.set(index, value);
        onChanged();
      } else {
        variablesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public Builder setVariables(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder builderForValue) {
      if (variablesBuilder_ == null) {
        ensureVariablesIsMutable();
        variables_.set(index, builderForValue.build());
        onChanged();
      } else {
        variablesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public Builder addVariables(it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap value) {
      if (variablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariablesIsMutable();
        variables_.add(value);
        onChanged();
      } else {
        variablesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public Builder addVariables(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap value) {
      if (variablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariablesIsMutable();
        variables_.add(index, value);
        onChanged();
      } else {
        variablesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public Builder addVariables(
        it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder builderForValue) {
      if (variablesBuilder_ == null) {
        ensureVariablesIsMutable();
        variables_.add(builderForValue.build());
        onChanged();
      } else {
        variablesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public Builder addVariables(
        int index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder builderForValue) {
      if (variablesBuilder_ == null) {
        ensureVariablesIsMutable();
        variables_.add(index, builderForValue.build());
        onChanged();
      } else {
        variablesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public Builder addAllVariables(
        java.lang.Iterable<? extends it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap> values) {
      if (variablesBuilder_ == null) {
        ensureVariablesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, variables_);
        onChanged();
      } else {
        variablesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public Builder clearVariables() {
      if (variablesBuilder_ == null) {
        variables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        variablesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public Builder removeVariables(int index) {
      if (variablesBuilder_ == null) {
        ensureVariablesIsMutable();
        variables_.remove(index);
        onChanged();
      } else {
        variablesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder getVariablesBuilder(
        int index) {
      return getVariablesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder getVariablesOrBuilder(
        int index) {
      if (variablesBuilder_ == null) {
        return variables_.get(index);  } else {
        return variablesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public java.util.List<? extends it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> 
         getVariablesOrBuilderList() {
      if (variablesBuilder_ != null) {
        return variablesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(variables_);
      }
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder addVariablesBuilder() {
      return getVariablesFieldBuilder().addBuilder(
          it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.getDefaultInstance());
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder addVariablesBuilder(
        int index) {
      return getVariablesFieldBuilder().addBuilder(
          index, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.getDefaultInstance());
    }
    /**
     * <code>repeated .it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceMap variables = 4;</code>
     */
    public java.util.List<it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder> 
         getVariablesBuilderList() {
      return getVariablesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder> 
        getVariablesFieldBuilder() {
      if (variablesBuilder_ == null) {
        variablesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMap.Builder, it.achdjian.saucer.luminous.protobuf.HomeassistantServiceMapOrBuilder>(
                variables_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        variables_ = null;
      }
      return variablesBuilder_;
    }

    private boolean isEvent_ ;
    /**
     * <code>bool is_event = 5;</code>
     * @return The isEvent.
     */
    @java.lang.Override
    public boolean getIsEvent() {
      return isEvent_;
    }
    /**
     * <code>bool is_event = 5;</code>
     * @param value The isEvent to set.
     * @return This builder for chaining.
     */
    public Builder setIsEvent(boolean value) {
      
      isEvent_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_event = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsEvent() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isEvent_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceResponse)
  }

  // @@protoc_insertion_point(class_scope:it.achdjian.sottovasoluminoso.protobuf.java.HomeassistantServiceResponse)
  private static final it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse();
  }

  public static it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HomeassistantServiceResponse>
      PARSER = new com.google.protobuf.AbstractParser<HomeassistantServiceResponse>() {
    @java.lang.Override
    public HomeassistantServiceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HomeassistantServiceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HomeassistantServiceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public it.achdjian.saucer.luminous.protobuf.HomeassistantServiceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

