//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: api.proto

package it.achdjian.saucer.luminous.protobuf;

@kotlin.jvm.JvmName("-initializehomeAssistantStateResponse")
public inline fun homeAssistantStateResponse(block: it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponseKt.Dsl.() -> kotlin.Unit): it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponse =
  it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponseKt.Dsl._create(it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponse.newBuilder()).apply { block() }._build()
public object HomeAssistantStateResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponse = _builder.build()

    /**
     * <code>string entity_id = 1;</code>
     */
    public var entityId: kotlin.String
      @JvmName("getEntityId")
      get() = _builder.getEntityId()
      @JvmName("setEntityId")
      set(value) {
        _builder.setEntityId(value)
      }
    /**
     * <code>string entity_id = 1;</code>
     */
    public fun clearEntityId() {
      _builder.clearEntityId()
    }

    /**
     * <code>string state = 2;</code>
     */
    public var state: kotlin.String
      @JvmName("getState")
      get() = _builder.getState()
      @JvmName("setState")
      set(value) {
        _builder.setState(value)
      }
    /**
     * <code>string state = 2;</code>
     */
    public fun clearState() {
      _builder.clearState()
    }

    /**
     * <code>string attribute = 3;</code>
     */
    public var attribute: kotlin.String
      @JvmName("getAttribute")
      get() = _builder.getAttribute()
      @JvmName("setAttribute")
      set(value) {
        _builder.setAttribute(value)
      }
    /**
     * <code>string attribute = 3;</code>
     */
    public fun clearAttribute() {
      _builder.clearAttribute()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponse.copy(block: it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponseKt.Dsl.() -> kotlin.Unit): it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponse =
  it.achdjian.saucer.luminous.protobuf.HomeAssistantStateResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

