// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package it.achdjian.saucer.luminous.protobuf;

public interface LockStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:it.achdjian.sottovasoluminoso.protobuf.java.LockStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed32 key = 1;</code>
   * @return The key.
   */
  int getKey();

  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.LockState state = 2;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.it.achdjian.sottovasoluminoso.protobuf.java.LockState state = 2;</code>
   * @return The state.
   */
  it.achdjian.saucer.luminous.protobuf.LockState getState();
}
